// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// Each item has either result or error. An item failure does not change the batch HTTP 200 status.
    /// </summary>
    public partial class BatchVerificationItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchVerificationItem" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="stages">stages</param>
        /// <param name="error">error</param>
        /// <param name="result">result</param>
        [JsonConstructor]
        public BatchVerificationItem(string email, List<VerificationStage> stages, Option<BatchVerificationError?> error = default, Option<VerificationResult?> result = default)
        {
            Email = email;
            Stages = stages;
            ErrorOption = error;
            ResultOption = result;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Stages
        /// </summary>
        [JsonPropertyName("stages")]
        public List<VerificationStage> Stages { get; set; }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BatchVerificationError?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public BatchVerificationError? Error { get { return this.ErrorOption.Value; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Result
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VerificationResult?> ResultOption { get; private set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [JsonPropertyName("result")]
        public VerificationResult? Result { get { return this.ResultOption.Value; } set { this.ResultOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchVerificationItem {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Stages: ").Append(Stages).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BatchVerificationItem" />
    /// </summary>
    public partial class BatchVerificationItemJsonConverter : JsonConverter<BatchVerificationItem>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchVerificationItemJsonConverter" /> class.
        /// </summary>
        public BatchVerificationItemJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="BatchVerificationItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BatchVerificationItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<List<VerificationStage>?> stages = default;
            Option<BatchVerificationError?> error = default;
            Option<VerificationResult?> result = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stages":
                            stages = new Option<List<VerificationStage>?>(JsonSerializer.Deserialize<List<VerificationStage>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error":
                            error = new Option<BatchVerificationError?>(JsonSerializer.Deserialize<BatchVerificationError>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "result":
                            result = new Option<VerificationResult?>(JsonSerializer.Deserialize<VerificationResult>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class BatchVerificationItem.", nameof(email));

            if (!stages.IsSet)
                throw new ArgumentException("Property is required for class BatchVerificationItem.", nameof(stages));

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class BatchVerificationItem.");

            if (stages.IsSet && stages.Value == null)
                throw new ArgumentNullException(nameof(stages), "Property is not nullable for class BatchVerificationItem.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class BatchVerificationItem.");

            if (result.IsSet && result.Value == null)
                throw new ArgumentNullException(nameof(result), "Property is not nullable for class BatchVerificationItem.");

            var reaconModelResult = new BatchVerificationItem(email.Value!, stages.Value!, error, result);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="BatchVerificationItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="batchVerificationItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BatchVerificationItem batchVerificationItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, batchVerificationItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BatchVerificationItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="batchVerificationItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BatchVerificationItem batchVerificationItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (batchVerificationItem.Email == null)
                throw new ArgumentNullException(nameof(batchVerificationItem.Email), "Property is required for class BatchVerificationItem.");

            if (batchVerificationItem.Stages == null)
                throw new ArgumentNullException(nameof(batchVerificationItem.Stages), "Property is required for class BatchVerificationItem.");

            if (batchVerificationItem.ErrorOption.IsSet && batchVerificationItem.Error == null)
                throw new ArgumentNullException(nameof(batchVerificationItem.Error), "Property is required for class BatchVerificationItem.");

            if (batchVerificationItem.ResultOption.IsSet && batchVerificationItem.Result == null)
                throw new ArgumentNullException(nameof(batchVerificationItem.Result), "Property is required for class BatchVerificationItem.");

            writer.WriteString("email", batchVerificationItem.Email);

            writer.WritePropertyName("stages");
            JsonSerializer.Serialize(writer, batchVerificationItem.Stages, jsonSerializerOptions);
            if (batchVerificationItem.ErrorOption.IsSet)
            {
                writer.WritePropertyName("error");
                JsonSerializer.Serialize(writer, batchVerificationItem.Error, jsonSerializerOptions);
            }
            if (batchVerificationItem.ResultOption.IsSet)
            {
                writer.WritePropertyName("result");
                JsonSerializer.Serialize(writer, batchVerificationItem.Result, jsonSerializerOptions);
            }

            foreach (var property in batchVerificationItem.AdditionalProperties)
            {
                if (property.Key == "email" || property.Key == "stages" || property.Key == "error" || property.Key == "result") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
