// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// BindWebflowFormRequest
    /// </summary>
    public partial class BindWebflowFormRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BindWebflowFormRequest" /> class.
        /// </summary>
        /// <param name="capability">capability</param>
        /// <param name="connectionId">connectionId</param>
        /// <param name="fieldMapping">fieldMapping</param>
        /// <param name="formId">formId</param>
        [JsonConstructor]
        public BindWebflowFormRequest(CapabilityEnum capability, Guid connectionId, Dictionary<string, string> fieldMapping, string formId)
        {
            Capability = capability;
            ConnectionId = connectionId;
            FieldMapping = fieldMapping;
            FormId = formId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Capability
        /// </summary>
        public enum CapabilityEnum
        {
            /// <summary>
            /// Enum EmailFind for value: email.find
            /// </summary>
            EmailFind = 1,

            /// <summary>
            /// Enum EmailVerify for value: email.verify
            /// </summary>
            EmailVerify = 2,

            /// <summary>
            /// Enum DomainSearch for value: domain.search
            /// </summary>
            DomainSearch = 3
        }

        /// <summary>
        /// Returns a <see cref="CapabilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CapabilityEnum CapabilityEnumFromString(string value)
        {
            if (value.Equals("email.find"))
                return CapabilityEnum.EmailFind;

            if (value.Equals("email.verify"))
                return CapabilityEnum.EmailVerify;

            if (value.Equals("domain.search"))
                return CapabilityEnum.DomainSearch;

            throw new NotImplementedException($"Could not convert value to type CapabilityEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CapabilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CapabilityEnum? CapabilityEnumFromStringOrDefault(string value)
        {
            if (value.Equals("email.find"))
                return CapabilityEnum.EmailFind;

            if (value.Equals("email.verify"))
                return CapabilityEnum.EmailVerify;

            if (value.Equals("domain.search"))
                return CapabilityEnum.DomainSearch;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CapabilityEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CapabilityEnumToJsonValue(CapabilityEnum value)
        {
            if (value == CapabilityEnum.EmailFind)
                return "email.find";

            if (value == CapabilityEnum.EmailVerify)
                return "email.verify";

            if (value == CapabilityEnum.DomainSearch)
                return "domain.search";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Capability
        /// </summary>
        [JsonPropertyName("capability")]
        public CapabilityEnum Capability { get; set; }

        /// <summary>
        /// Gets or Sets ConnectionId
        /// </summary>
        [JsonPropertyName("connectionId")]
        public Guid ConnectionId { get; set; }

        /// <summary>
        /// Gets or Sets FieldMapping
        /// </summary>
        [JsonPropertyName("fieldMapping")]
        public Dictionary<string, string> FieldMapping { get; set; }

        /// <summary>
        /// Gets or Sets FormId
        /// </summary>
        [JsonPropertyName("formId")]
        public string FormId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BindWebflowFormRequest {\n");
            sb.Append("  Capability: ").Append(Capability).Append("\n");
            sb.Append("  ConnectionId: ").Append(ConnectionId).Append("\n");
            sb.Append("  FieldMapping: ").Append(FieldMapping).Append("\n");
            sb.Append("  FormId: ").Append(FormId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FormId (string) maxLength
            if (this.FormId != null && this.FormId.Length > 100)
            {
                yield return new ValidationResult("Invalid value for FormId, length must be less than 100.", new [] { "FormId" });
            }

            // FormId (string) minLength
            if (this.FormId != null && this.FormId.Length < 3)
            {
                yield return new ValidationResult("Invalid value for FormId, length must be greater than 3.", new [] { "FormId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BindWebflowFormRequest" />
    /// </summary>
    public partial class BindWebflowFormRequestJsonConverter : JsonConverter<BindWebflowFormRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BindWebflowFormRequestJsonConverter" /> class.
        /// </summary>
        public BindWebflowFormRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="BindWebflowFormRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BindWebflowFormRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<BindWebflowFormRequest.CapabilityEnum?> capability = default;
            Option<Guid?> connectionId = default;
            Option<Dictionary<string, string>?> fieldMapping = default;
            Option<string?> formId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "capability":
                            string? capabilityRawValue = utf8JsonReader.GetString();
                            if (capabilityRawValue != null)
                            {
                                BindWebflowFormRequest.CapabilityEnum? capabilityValue = BindWebflowFormRequest.CapabilityEnumFromStringOrDefault(capabilityRawValue);
                                if (capabilityValue == null)
                                    throw new JsonException();
                                capability = new Option<BindWebflowFormRequest.CapabilityEnum?>(capabilityValue);
                            }
                            break;
                        case "connectionId":
                            connectionId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "fieldMapping":
                            fieldMapping = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "formId":
                            formId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!capability.IsSet)
                throw new ArgumentException("Property is required for class BindWebflowFormRequest.", nameof(capability));

            if (!connectionId.IsSet)
                throw new ArgumentException("Property is required for class BindWebflowFormRequest.", nameof(connectionId));

            if (!fieldMapping.IsSet)
                throw new ArgumentException("Property is required for class BindWebflowFormRequest.", nameof(fieldMapping));

            if (!formId.IsSet)
                throw new ArgumentException("Property is required for class BindWebflowFormRequest.", nameof(formId));

            if (capability.IsSet && capability.Value == null)
                throw new ArgumentNullException(nameof(capability), "Property is not nullable for class BindWebflowFormRequest.");

            if (connectionId.IsSet && connectionId.Value == null)
                throw new ArgumentNullException(nameof(connectionId), "Property is not nullable for class BindWebflowFormRequest.");

            if (fieldMapping.IsSet && fieldMapping.Value == null)
                throw new ArgumentNullException(nameof(fieldMapping), "Property is not nullable for class BindWebflowFormRequest.");

            if (formId.IsSet && formId.Value == null)
                throw new ArgumentNullException(nameof(formId), "Property is not nullable for class BindWebflowFormRequest.");

            return new BindWebflowFormRequest(capability.Value!.Value!, connectionId.Value!.Value!, fieldMapping.Value!, formId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BindWebflowFormRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bindWebflowFormRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BindWebflowFormRequest bindWebflowFormRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bindWebflowFormRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BindWebflowFormRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bindWebflowFormRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BindWebflowFormRequest bindWebflowFormRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bindWebflowFormRequest.FieldMapping == null)
                throw new ArgumentNullException(nameof(bindWebflowFormRequest.FieldMapping), "Property is required for class BindWebflowFormRequest.");

            if (bindWebflowFormRequest.FormId == null)
                throw new ArgumentNullException(nameof(bindWebflowFormRequest.FormId), "Property is required for class BindWebflowFormRequest.");

            var capabilityRawValue = BindWebflowFormRequest.CapabilityEnumToJsonValue(bindWebflowFormRequest.Capability);
            writer.WriteString("capability", capabilityRawValue);
            writer.WriteString("connectionId", bindWebflowFormRequest.ConnectionId);

            writer.WritePropertyName("fieldMapping");
            JsonSerializer.Serialize(writer, bindWebflowFormRequest.FieldMapping, jsonSerializerOptions);
            writer.WriteString("formId", bindWebflowFormRequest.FormId);
        }
    }
}
