// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ConfigureCrmSyncRequestConfigurationHubspotDeal
    /// </summary>
    public partial class ConfigureCrmSyncRequestConfigurationHubspotDeal : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureCrmSyncRequestConfigurationHubspotDeal" /> class.
        /// </summary>
        /// <param name="enabled">enabled</param>
        /// <param name="ownerId">ownerId</param>
        /// <param name="pipeline">pipeline</param>
        /// <param name="stage">stage</param>
        [JsonConstructor]
        public ConfigureCrmSyncRequestConfigurationHubspotDeal(bool enabled, string? ownerId = default, string? pipeline = default, string? stage = default)
        {
            Enabled = enabled;
            OwnerId = ownerId;
            Pipeline = pipeline;
            Stage = stage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets OwnerId
        /// </summary>
        [JsonPropertyName("ownerId")]
        public string? OwnerId { get; set; }

        /// <summary>
        /// Gets or Sets Pipeline
        /// </summary>
        [JsonPropertyName("pipeline")]
        public string? Pipeline { get; set; }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [JsonPropertyName("stage")]
        public string? Stage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigureCrmSyncRequestConfigurationHubspotDeal {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  Pipeline: ").Append(Pipeline).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConfigureCrmSyncRequestConfigurationHubspotDeal" />
    /// </summary>
    public partial class ConfigureCrmSyncRequestConfigurationHubspotDealJsonConverter : JsonConverter<ConfigureCrmSyncRequestConfigurationHubspotDeal>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureCrmSyncRequestConfigurationHubspotDealJsonConverter" /> class.
        /// </summary>
        public ConfigureCrmSyncRequestConfigurationHubspotDealJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ConfigureCrmSyncRequestConfigurationHubspotDeal" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConfigureCrmSyncRequestConfigurationHubspotDeal Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> enabled = default;
            Option<string?> ownerId = default;
            Option<string?> pipeline = default;
            Option<string?> stage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ownerId":
                            ownerId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "pipeline":
                            pipeline = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "stage":
                            stage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!enabled.IsSet)
                throw new ArgumentException("Property is required for class ConfigureCrmSyncRequestConfigurationHubspotDeal.", nameof(enabled));

            if (!ownerId.IsSet)
                throw new ArgumentException("Property is required for class ConfigureCrmSyncRequestConfigurationHubspotDeal.", nameof(ownerId));

            if (!pipeline.IsSet)
                throw new ArgumentException("Property is required for class ConfigureCrmSyncRequestConfigurationHubspotDeal.", nameof(pipeline));

            if (!stage.IsSet)
                throw new ArgumentException("Property is required for class ConfigureCrmSyncRequestConfigurationHubspotDeal.", nameof(stage));

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class ConfigureCrmSyncRequestConfigurationHubspotDeal.");

            return new ConfigureCrmSyncRequestConfigurationHubspotDeal(enabled.Value!.Value!, ownerId.Value!, pipeline.Value!, stage.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ConfigureCrmSyncRequestConfigurationHubspotDeal" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="configureCrmSyncRequestConfigurationHubspotDeal"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConfigureCrmSyncRequestConfigurationHubspotDeal configureCrmSyncRequestConfigurationHubspotDeal, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, configureCrmSyncRequestConfigurationHubspotDeal, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConfigureCrmSyncRequestConfigurationHubspotDeal" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="configureCrmSyncRequestConfigurationHubspotDeal"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConfigureCrmSyncRequestConfigurationHubspotDeal configureCrmSyncRequestConfigurationHubspotDeal, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("enabled", configureCrmSyncRequestConfigurationHubspotDeal.Enabled);

            if (configureCrmSyncRequestConfigurationHubspotDeal.OwnerId != null)
                writer.WriteString("ownerId", configureCrmSyncRequestConfigurationHubspotDeal.OwnerId);
            else
                writer.WriteNull("ownerId");

            if (configureCrmSyncRequestConfigurationHubspotDeal.Pipeline != null)
                writer.WriteString("pipeline", configureCrmSyncRequestConfigurationHubspotDeal.Pipeline);
            else
                writer.WriteNull("pipeline");

            if (configureCrmSyncRequestConfigurationHubspotDeal.Stage != null)
                writer.WriteString("stage", configureCrmSyncRequestConfigurationHubspotDeal.Stage);
            else
                writer.WriteNull("stage");
        }
    }
}
