// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ConfigureWebflowFormRequest
    /// </summary>
    public partial class ConfigureWebflowFormRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureWebflowFormRequest" /> class.
        /// </summary>
        /// <param name="accessToken">accessToken</param>
        /// <param name="capability">capability</param>
        /// <param name="fieldMapping">fieldMapping</param>
        /// <param name="formId">formId</param>
        /// <param name="label">label</param>
        /// <param name="siteId">siteId</param>
        /// <param name="mode">mode</param>
        [JsonConstructor]
        public ConfigureWebflowFormRequest(string accessToken, CapabilityEnum capability, Dictionary<string, string> fieldMapping, string formId, string label, string siteId, Option<ModeEnum?> mode = default)
        {
            AccessToken = accessToken;
            Capability = capability;
            FieldMapping = fieldMapping;
            FormId = formId;
            Label = label;
            SiteId = siteId;
            ModeOption = mode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Capability
        /// </summary>
        public enum CapabilityEnum
        {
            /// <summary>
            /// Enum EmailFind for value: email.find
            /// </summary>
            EmailFind = 1,

            /// <summary>
            /// Enum EmailVerify for value: email.verify
            /// </summary>
            EmailVerify = 2,

            /// <summary>
            /// Enum DomainSearch for value: domain.search
            /// </summary>
            DomainSearch = 3
        }

        /// <summary>
        /// Returns a <see cref="CapabilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CapabilityEnum CapabilityEnumFromString(string value)
        {
            if (value.Equals("email.find"))
                return CapabilityEnum.EmailFind;

            if (value.Equals("email.verify"))
                return CapabilityEnum.EmailVerify;

            if (value.Equals("domain.search"))
                return CapabilityEnum.DomainSearch;

            throw new NotImplementedException($"Could not convert value to type CapabilityEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CapabilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CapabilityEnum? CapabilityEnumFromStringOrDefault(string value)
        {
            if (value.Equals("email.find"))
                return CapabilityEnum.EmailFind;

            if (value.Equals("email.verify"))
                return CapabilityEnum.EmailVerify;

            if (value.Equals("domain.search"))
                return CapabilityEnum.DomainSearch;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CapabilityEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CapabilityEnumToJsonValue(CapabilityEnum value)
        {
            if (value == CapabilityEnum.EmailFind)
                return "email.find";

            if (value == CapabilityEnum.EmailVerify)
                return "email.verify";

            if (value == CapabilityEnum.DomainSearch)
                return "domain.search";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Capability
        /// </summary>
        [JsonPropertyName("capability")]
        public CapabilityEnum Capability { get; set; }

        /// <summary>
        /// Defines Mode
        /// </summary>
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Live for value: live
            /// </summary>
            Live = 1,

            /// <summary>
            /// Enum Emulated for value: emulated
            /// </summary>
            Emulated = 2
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ModeEnum ModeEnumFromString(string value)
        {
            if (value.Equals("live"))
                return ModeEnum.Live;

            if (value.Equals("emulated"))
                return ModeEnum.Emulated;

            throw new NotImplementedException($"Could not convert value to type ModeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ModeEnum? ModeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("live"))
                return ModeEnum.Live;

            if (value.Equals("emulated"))
                return ModeEnum.Emulated;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ModeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ModeEnumToJsonValue(ModeEnum? value)
        {
            if (value == ModeEnum.Live)
                return "live";

            if (value == ModeEnum.Emulated)
                return "emulated";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Mode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ModeEnum?> ModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [JsonPropertyName("mode")]
        public ModeEnum? Mode { get { return this.ModeOption.Value; } set { this.ModeOption = new(value); } }

        /// <summary>
        /// Gets or Sets AccessToken
        /// </summary>
        [JsonPropertyName("accessToken")]
        public string AccessToken { get; set; }

        /// <summary>
        /// Gets or Sets FieldMapping
        /// </summary>
        [JsonPropertyName("fieldMapping")]
        public Dictionary<string, string> FieldMapping { get; set; }

        /// <summary>
        /// Gets or Sets FormId
        /// </summary>
        [JsonPropertyName("formId")]
        public string FormId { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets SiteId
        /// </summary>
        [JsonPropertyName("siteId")]
        public string SiteId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigureWebflowFormRequest {\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("  Capability: ").Append(Capability).Append("\n");
            sb.Append("  FieldMapping: ").Append(FieldMapping).Append("\n");
            sb.Append("  FormId: ").Append(FormId).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AccessToken (string) maxLength
            if (this.AccessToken != null && this.AccessToken.Length > 16384)
            {
                yield return new ValidationResult("Invalid value for AccessToken, length must be less than 16384.", new [] { "AccessToken" });
            }

            // AccessToken (string) minLength
            if (this.AccessToken != null && this.AccessToken.Length < 24)
            {
                yield return new ValidationResult("Invalid value for AccessToken, length must be greater than 24.", new [] { "AccessToken" });
            }

            // FormId (string) maxLength
            if (this.FormId != null && this.FormId.Length > 100)
            {
                yield return new ValidationResult("Invalid value for FormId, length must be less than 100.", new [] { "FormId" });
            }

            // FormId (string) minLength
            if (this.FormId != null && this.FormId.Length < 3)
            {
                yield return new ValidationResult("Invalid value for FormId, length must be greater than 3.", new [] { "FormId" });
            }

            // Label (string) maxLength
            if (this.Label != null && this.Label.Length > 120)
            {
                yield return new ValidationResult("Invalid value for Label, length must be less than 120.", new [] { "Label" });
            }

            // Label (string) minLength
            if (this.Label != null && this.Label.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Label, length must be greater than 1.", new [] { "Label" });
            }

            // SiteId (string) maxLength
            if (this.SiteId != null && this.SiteId.Length > 100)
            {
                yield return new ValidationResult("Invalid value for SiteId, length must be less than 100.", new [] { "SiteId" });
            }

            // SiteId (string) minLength
            if (this.SiteId != null && this.SiteId.Length < 3)
            {
                yield return new ValidationResult("Invalid value for SiteId, length must be greater than 3.", new [] { "SiteId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConfigureWebflowFormRequest" />
    /// </summary>
    public partial class ConfigureWebflowFormRequestJsonConverter : JsonConverter<ConfigureWebflowFormRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureWebflowFormRequestJsonConverter" /> class.
        /// </summary>
        public ConfigureWebflowFormRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ConfigureWebflowFormRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConfigureWebflowFormRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> accessToken = default;
            Option<ConfigureWebflowFormRequest.CapabilityEnum?> capability = default;
            Option<Dictionary<string, string>?> fieldMapping = default;
            Option<string?> formId = default;
            Option<string?> label = default;
            Option<string?> siteId = default;
            Option<ConfigureWebflowFormRequest.ModeEnum?> mode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "accessToken":
                            accessToken = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "capability":
                            string? capabilityRawValue = utf8JsonReader.GetString();
                            if (capabilityRawValue != null)
                            {
                                ConfigureWebflowFormRequest.CapabilityEnum? capabilityValue = ConfigureWebflowFormRequest.CapabilityEnumFromStringOrDefault(capabilityRawValue);
                                if (capabilityValue == null)
                                    throw new JsonException();
                                capability = new Option<ConfigureWebflowFormRequest.CapabilityEnum?>(capabilityValue);
                            }
                            break;
                        case "fieldMapping":
                            fieldMapping = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "formId":
                            formId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "siteId":
                            siteId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mode":
                            string? modeRawValue = utf8JsonReader.GetString();
                            if (modeRawValue != null)
                            {
                                ConfigureWebflowFormRequest.ModeEnum? modeValue = ConfigureWebflowFormRequest.ModeEnumFromStringOrDefault(modeRawValue);
                                if (modeValue == null)
                                    throw new JsonException();
                                mode = new Option<ConfigureWebflowFormRequest.ModeEnum?>(modeValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!accessToken.IsSet)
                throw new ArgumentException("Property is required for class ConfigureWebflowFormRequest.", nameof(accessToken));

            if (!capability.IsSet)
                throw new ArgumentException("Property is required for class ConfigureWebflowFormRequest.", nameof(capability));

            if (!fieldMapping.IsSet)
                throw new ArgumentException("Property is required for class ConfigureWebflowFormRequest.", nameof(fieldMapping));

            if (!formId.IsSet)
                throw new ArgumentException("Property is required for class ConfigureWebflowFormRequest.", nameof(formId));

            if (!label.IsSet)
                throw new ArgumentException("Property is required for class ConfigureWebflowFormRequest.", nameof(label));

            if (!siteId.IsSet)
                throw new ArgumentException("Property is required for class ConfigureWebflowFormRequest.", nameof(siteId));

            if (accessToken.IsSet && accessToken.Value == null)
                throw new ArgumentNullException(nameof(accessToken), "Property is not nullable for class ConfigureWebflowFormRequest.");

            if (capability.IsSet && capability.Value == null)
                throw new ArgumentNullException(nameof(capability), "Property is not nullable for class ConfigureWebflowFormRequest.");

            if (fieldMapping.IsSet && fieldMapping.Value == null)
                throw new ArgumentNullException(nameof(fieldMapping), "Property is not nullable for class ConfigureWebflowFormRequest.");

            if (formId.IsSet && formId.Value == null)
                throw new ArgumentNullException(nameof(formId), "Property is not nullable for class ConfigureWebflowFormRequest.");

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class ConfigureWebflowFormRequest.");

            if (siteId.IsSet && siteId.Value == null)
                throw new ArgumentNullException(nameof(siteId), "Property is not nullable for class ConfigureWebflowFormRequest.");

            if (mode.IsSet && mode.Value == null)
                throw new ArgumentNullException(nameof(mode), "Property is not nullable for class ConfigureWebflowFormRequest.");

            return new ConfigureWebflowFormRequest(accessToken.Value!, capability.Value!.Value!, fieldMapping.Value!, formId.Value!, label.Value!, siteId.Value!, mode);
        }

        /// <summary>
        /// Serializes a <see cref="ConfigureWebflowFormRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="configureWebflowFormRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConfigureWebflowFormRequest configureWebflowFormRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, configureWebflowFormRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConfigureWebflowFormRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="configureWebflowFormRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConfigureWebflowFormRequest configureWebflowFormRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (configureWebflowFormRequest.AccessToken == null)
                throw new ArgumentNullException(nameof(configureWebflowFormRequest.AccessToken), "Property is required for class ConfigureWebflowFormRequest.");

            if (configureWebflowFormRequest.FieldMapping == null)
                throw new ArgumentNullException(nameof(configureWebflowFormRequest.FieldMapping), "Property is required for class ConfigureWebflowFormRequest.");

            if (configureWebflowFormRequest.FormId == null)
                throw new ArgumentNullException(nameof(configureWebflowFormRequest.FormId), "Property is required for class ConfigureWebflowFormRequest.");

            if (configureWebflowFormRequest.Label == null)
                throw new ArgumentNullException(nameof(configureWebflowFormRequest.Label), "Property is required for class ConfigureWebflowFormRequest.");

            if (configureWebflowFormRequest.SiteId == null)
                throw new ArgumentNullException(nameof(configureWebflowFormRequest.SiteId), "Property is required for class ConfigureWebflowFormRequest.");

            writer.WriteString("accessToken", configureWebflowFormRequest.AccessToken);

            var capabilityRawValue = ConfigureWebflowFormRequest.CapabilityEnumToJsonValue(configureWebflowFormRequest.Capability);
            writer.WriteString("capability", capabilityRawValue);
            writer.WritePropertyName("fieldMapping");
            JsonSerializer.Serialize(writer, configureWebflowFormRequest.FieldMapping, jsonSerializerOptions);
            writer.WriteString("formId", configureWebflowFormRequest.FormId);

            writer.WriteString("label", configureWebflowFormRequest.Label);

            writer.WriteString("siteId", configureWebflowFormRequest.SiteId);

            if (configureWebflowFormRequest.ModeOption.IsSet)
            {
                if (configureWebflowFormRequest.Mode is null) throw new JsonException("mode cannot be null; omit it instead.");
                else
                {
                    var modeRawValue = ConfigureWebflowFormRequest.ModeEnumToJsonValue(configureWebflowFormRequest.Mode.Value);
                    writer.WriteString("mode", modeRawValue);
                }
            }
        }
    }
}
