// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ConfigureTeamsWorkflowRequest
    /// </summary>
    public partial class ConfigureTeamsWorkflowRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureTeamsWorkflowRequest" /> class.
        /// </summary>
        /// <param name="label">label</param>
        /// <param name="webhookUrl">webhookUrl</param>
        /// <param name="mode">mode</param>
        [JsonConstructor]
        public ConfigureTeamsWorkflowRequest(string label, string webhookUrl, Option<ModeEnum?> mode = default)
        {
            Label = label;
            WebhookUrl = webhookUrl;
            ModeOption = mode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Mode
        /// </summary>
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Live for value: live
            /// </summary>
            Live = 1,

            /// <summary>
            /// Enum Emulated for value: emulated
            /// </summary>
            Emulated = 2
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ModeEnum ModeEnumFromString(string value)
        {
            if (value.Equals("live"))
                return ModeEnum.Live;

            if (value.Equals("emulated"))
                return ModeEnum.Emulated;

            throw new NotImplementedException($"Could not convert value to type ModeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ModeEnum? ModeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("live"))
                return ModeEnum.Live;

            if (value.Equals("emulated"))
                return ModeEnum.Emulated;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ModeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ModeEnumToJsonValue(ModeEnum? value)
        {
            if (value == ModeEnum.Live)
                return "live";

            if (value == ModeEnum.Emulated)
                return "emulated";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Mode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ModeEnum?> ModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [JsonPropertyName("mode")]
        public ModeEnum? Mode { get { return this.ModeOption.Value; } set { this.ModeOption = new(value); } }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [JsonPropertyName("webhookUrl")]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigureTeamsWorkflowRequest {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Label (string) maxLength
            if (this.Label != null && this.Label.Length > 120)
            {
                yield return new ValidationResult("Invalid value for Label, length must be less than 120.", new [] { "Label" });
            }

            // Label (string) minLength
            if (this.Label != null && this.Label.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Label, length must be greater than 1.", new [] { "Label" });
            }

            // WebhookUrl (string) maxLength
            if (this.WebhookUrl != null && this.WebhookUrl.Length > 8192)
            {
                yield return new ValidationResult("Invalid value for WebhookUrl, length must be less than 8192.", new [] { "WebhookUrl" });
            }

            // WebhookUrl (string) minLength
            if (this.WebhookUrl != null && this.WebhookUrl.Length < 8)
            {
                yield return new ValidationResult("Invalid value for WebhookUrl, length must be greater than 8.", new [] { "WebhookUrl" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConfigureTeamsWorkflowRequest" />
    /// </summary>
    public partial class ConfigureTeamsWorkflowRequestJsonConverter : JsonConverter<ConfigureTeamsWorkflowRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureTeamsWorkflowRequestJsonConverter" /> class.
        /// </summary>
        public ConfigureTeamsWorkflowRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ConfigureTeamsWorkflowRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConfigureTeamsWorkflowRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> label = default;
            Option<string?> webhookUrl = default;
            Option<ConfigureTeamsWorkflowRequest.ModeEnum?> mode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "webhookUrl":
                            webhookUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mode":
                            string? modeRawValue = utf8JsonReader.GetString();
                            if (modeRawValue != null)
                            {
                                ConfigureTeamsWorkflowRequest.ModeEnum? modeValue = ConfigureTeamsWorkflowRequest.ModeEnumFromStringOrDefault(modeRawValue);
                                if (modeValue == null)
                                    throw new JsonException();
                                mode = new Option<ConfigureTeamsWorkflowRequest.ModeEnum?>(modeValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!label.IsSet)
                throw new ArgumentException("Property is required for class ConfigureTeamsWorkflowRequest.", nameof(label));

            if (!webhookUrl.IsSet)
                throw new ArgumentException("Property is required for class ConfigureTeamsWorkflowRequest.", nameof(webhookUrl));

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class ConfigureTeamsWorkflowRequest.");

            if (webhookUrl.IsSet && webhookUrl.Value == null)
                throw new ArgumentNullException(nameof(webhookUrl), "Property is not nullable for class ConfigureTeamsWorkflowRequest.");

            if (mode.IsSet && mode.Value == null)
                throw new ArgumentNullException(nameof(mode), "Property is not nullable for class ConfigureTeamsWorkflowRequest.");

            return new ConfigureTeamsWorkflowRequest(label.Value!, webhookUrl.Value!, mode);
        }

        /// <summary>
        /// Serializes a <see cref="ConfigureTeamsWorkflowRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="configureTeamsWorkflowRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConfigureTeamsWorkflowRequest configureTeamsWorkflowRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, configureTeamsWorkflowRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConfigureTeamsWorkflowRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="configureTeamsWorkflowRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConfigureTeamsWorkflowRequest configureTeamsWorkflowRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (configureTeamsWorkflowRequest.Label == null)
                throw new ArgumentNullException(nameof(configureTeamsWorkflowRequest.Label), "Property is required for class ConfigureTeamsWorkflowRequest.");

            if (configureTeamsWorkflowRequest.WebhookUrl == null)
                throw new ArgumentNullException(nameof(configureTeamsWorkflowRequest.WebhookUrl), "Property is required for class ConfigureTeamsWorkflowRequest.");

            writer.WriteString("label", configureTeamsWorkflowRequest.Label);

            writer.WriteString("webhookUrl", configureTeamsWorkflowRequest.WebhookUrl);

            if (configureTeamsWorkflowRequest.ModeOption.IsSet)
            {
                if (configureTeamsWorkflowRequest.Mode is null) throw new JsonException("mode cannot be null; omit it instead.");
                else
                {
                    var modeRawValue = ConfigureTeamsWorkflowRequest.ModeEnumToJsonValue(configureTeamsWorkflowRequest.Mode.Value);
                    writer.WriteString("mode", modeRawValue);
                }
            }
        }
    }
}
