// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// CreateLeadRequest
    /// </summary>
    public partial class CreateLeadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLeadRequest" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="company">company</param>
        /// <param name="person">person</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public CreateLeadRequest(string email, Option<CreateLeadRequestCompany?> company = default, Option<CreateLeadRequestPerson?> person = default, Option<List<string>?> tags = default)
        {
            Email = email;
            CompanyOption = company;
            PersonOption = person;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Used to track the state of Company
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CreateLeadRequestCompany?> CompanyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Company
        /// </summary>
        [JsonPropertyName("company")]
        public CreateLeadRequestCompany? Company { get { return this.CompanyOption.Value; } set { this.CompanyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Person
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CreateLeadRequestPerson?> PersonOption { get; private set; }

        /// <summary>
        /// Gets or Sets Person
        /// </summary>
        [JsonPropertyName("person")]
        public CreateLeadRequestPerson? Person { get { return this.PersonOption.Value; } set { this.PersonOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string>? Tags { get { return this.TagsOption.Value; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateLeadRequest {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  Person: ").Append(Person).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateLeadRequest" />
    /// </summary>
    public partial class CreateLeadRequestJsonConverter : JsonConverter<CreateLeadRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLeadRequestJsonConverter" /> class.
        /// </summary>
        public CreateLeadRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateLeadRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateLeadRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<CreateLeadRequestCompany?> company = default;
            Option<CreateLeadRequestPerson?> person = default;
            Option<List<string>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "company":
                            company = new Option<CreateLeadRequestCompany?>(JsonSerializer.Deserialize<CreateLeadRequestCompany>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "person":
                            person = new Option<CreateLeadRequestPerson?>(JsonSerializer.Deserialize<CreateLeadRequestPerson>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class CreateLeadRequest.", nameof(email));

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class CreateLeadRequest.");

            if (company.IsSet && company.Value == null)
                throw new ArgumentNullException(nameof(company), "Property is not nullable for class CreateLeadRequest.");

            if (person.IsSet && person.Value == null)
                throw new ArgumentNullException(nameof(person), "Property is not nullable for class CreateLeadRequest.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class CreateLeadRequest.");

            return new CreateLeadRequest(email.Value!, company, person, tags);
        }

        /// <summary>
        /// Serializes a <see cref="CreateLeadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createLeadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateLeadRequest createLeadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createLeadRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateLeadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createLeadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateLeadRequest createLeadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createLeadRequest.Email == null)
                throw new ArgumentNullException(nameof(createLeadRequest.Email), "Property is required for class CreateLeadRequest.");

            if (createLeadRequest.CompanyOption.IsSet && createLeadRequest.Company == null)
                throw new ArgumentNullException(nameof(createLeadRequest.Company), "Property is required for class CreateLeadRequest.");

            if (createLeadRequest.PersonOption.IsSet && createLeadRequest.Person == null)
                throw new ArgumentNullException(nameof(createLeadRequest.Person), "Property is required for class CreateLeadRequest.");

            if (createLeadRequest.TagsOption.IsSet && createLeadRequest.Tags == null)
                throw new ArgumentNullException(nameof(createLeadRequest.Tags), "Property is required for class CreateLeadRequest.");

            writer.WriteString("email", createLeadRequest.Email);

            if (createLeadRequest.CompanyOption.IsSet)
            {
                writer.WritePropertyName("company");
                JsonSerializer.Serialize(writer, createLeadRequest.Company, jsonSerializerOptions);
            }
            if (createLeadRequest.PersonOption.IsSet)
            {
                writer.WritePropertyName("person");
                JsonSerializer.Serialize(writer, createLeadRequest.Person, jsonSerializerOptions);
            }
            if (createLeadRequest.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, createLeadRequest.Tags, jsonSerializerOptions);
            }
        }
    }
}
