// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// CreateLeadRequestCompany
    /// </summary>
    public partial class CreateLeadRequestCompany : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLeadRequestCompany" /> class.
        /// </summary>
        /// <param name="addresses">addresses</param>
        /// <param name="foundedOn">foundedOn</param>
        /// <param name="industry">industry</param>
        /// <param name="linkedin">linkedin</param>
        /// <param name="location">location</param>
        /// <param name="name">name</param>
        /// <param name="numberOfEmployees">numberOfEmployees</param>
        /// <param name="stock">stock</param>
        /// <param name="twitter">twitter</param>
        /// <param name="type">type</param>
        /// <param name="website">website</param>
        [JsonConstructor]
        public CreateLeadRequestCompany(Option<List<CompanyListResultsInnerAddressesInner>?> addresses = default, Option<string?> foundedOn = default, Option<string?> industry = default, Option<string?> linkedin = default, Option<string?> location = default, Option<string?> name = default, Option<int?> numberOfEmployees = default, Option<string?> stock = default, Option<string?> twitter = default, Option<string?> type = default, Option<string?> website = default)
        {
            AddressesOption = addresses;
            FoundedOnOption = foundedOn;
            IndustryOption = industry;
            LinkedinOption = linkedin;
            LocationOption = location;
            NameOption = name;
            NumberOfEmployeesOption = numberOfEmployees;
            StockOption = stock;
            TwitterOption = twitter;
            TypeOption = type;
            WebsiteOption = website;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Addresses
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CompanyListResultsInnerAddressesInner>?> AddressesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Addresses
        /// </summary>
        [JsonPropertyName("addresses")]
        public List<CompanyListResultsInnerAddressesInner>? Addresses { get { return this.AddressesOption.Value; } set { this.AddressesOption = new(value); } }

        /// <summary>
        /// Used to track the state of FoundedOn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FoundedOnOption { get; private set; }

        /// <summary>
        /// Gets or Sets FoundedOn
        /// </summary>
        [JsonPropertyName("founded_on")]
        public string? FoundedOn { get { return this.FoundedOnOption.Value; } set { this.FoundedOnOption = new(value); } }

        /// <summary>
        /// Used to track the state of Industry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IndustryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Industry
        /// </summary>
        [JsonPropertyName("industry")]
        public string? Industry { get { return this.IndustryOption.Value; } set { this.IndustryOption = new(value); } }

        /// <summary>
        /// Used to track the state of Linkedin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LinkedinOption { get; private set; }

        /// <summary>
        /// Gets or Sets Linkedin
        /// </summary>
        [JsonPropertyName("linkedin")]
        public string? Linkedin { get { return this.LinkedinOption.Value; } set { this.LinkedinOption = new(value); } }

        /// <summary>
        /// Used to track the state of Location
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [JsonPropertyName("location")]
        public string? Location { get { return this.LocationOption.Value; } set { this.LocationOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumberOfEmployees
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NumberOfEmployeesOption { get; private set; }

        /// <summary>
        /// Gets or Sets NumberOfEmployees
        /// </summary>
        [JsonPropertyName("number_of_employees")]
        public int? NumberOfEmployees { get { return this.NumberOfEmployeesOption.Value; } set { this.NumberOfEmployeesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Stock
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StockOption { get; private set; }

        /// <summary>
        /// Gets or Sets Stock
        /// </summary>
        [JsonPropertyName("stock")]
        public string? Stock { get { return this.StockOption.Value; } set { this.StockOption = new(value); } }

        /// <summary>
        /// Used to track the state of Twitter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TwitterOption { get; private set; }

        /// <summary>
        /// Gets or Sets Twitter
        /// </summary>
        [JsonPropertyName("twitter")]
        public string? Twitter { get { return this.TwitterOption.Value; } set { this.TwitterOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Website
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WebsiteOption { get; private set; }

        /// <summary>
        /// Gets or Sets Website
        /// </summary>
        [JsonPropertyName("website")]
        public string? Website { get { return this.WebsiteOption.Value; } set { this.WebsiteOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateLeadRequestCompany {\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  FoundedOn: ").Append(FoundedOn).Append("\n");
            sb.Append("  Industry: ").Append(Industry).Append("\n");
            sb.Append("  Linkedin: ").Append(Linkedin).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NumberOfEmployees: ").Append(NumberOfEmployees).Append("\n");
            sb.Append("  Stock: ").Append(Stock).Append("\n");
            sb.Append("  Twitter: ").Append(Twitter).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Website: ").Append(Website).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateLeadRequestCompany" />
    /// </summary>
    public partial class CreateLeadRequestCompanyJsonConverter : JsonConverter<CreateLeadRequestCompany>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLeadRequestCompanyJsonConverter" /> class.
        /// </summary>
        public CreateLeadRequestCompanyJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateLeadRequestCompany" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateLeadRequestCompany Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<CompanyListResultsInnerAddressesInner>?> addresses = default;
            Option<string?> foundedOn = default;
            Option<string?> industry = default;
            Option<string?> linkedin = default;
            Option<string?> location = default;
            Option<string?> name = default;
            Option<int?> numberOfEmployees = default;
            Option<string?> stock = default;
            Option<string?> twitter = default;
            Option<string?> type = default;
            Option<string?> website = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "addresses":
                            addresses = new Option<List<CompanyListResultsInnerAddressesInner>?>(JsonSerializer.Deserialize<List<CompanyListResultsInnerAddressesInner>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "founded_on":
                            foundedOn = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "industry":
                            industry = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "linkedin":
                            linkedin = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "location":
                            location = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "number_of_employees":
                            numberOfEmployees = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "stock":
                            stock = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "twitter":
                            twitter = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "website":
                            website = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new CreateLeadRequestCompany(addresses, foundedOn, industry, linkedin, location, name, numberOfEmployees, stock, twitter, type, website);
        }

        /// <summary>
        /// Serializes a <see cref="CreateLeadRequestCompany" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createLeadRequestCompany"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateLeadRequestCompany createLeadRequestCompany, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createLeadRequestCompany, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateLeadRequestCompany" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createLeadRequestCompany"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateLeadRequestCompany createLeadRequestCompany, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createLeadRequestCompany.AddressesOption.IsSet)
                if (createLeadRequestCompany.AddressesOption.Value != null)
                {
                    writer.WritePropertyName("addresses");
                    JsonSerializer.Serialize(writer, createLeadRequestCompany.Addresses, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("addresses");
            if (createLeadRequestCompany.FoundedOnOption.IsSet)
                if (createLeadRequestCompany.FoundedOnOption.Value != null)
                    writer.WriteString("founded_on", createLeadRequestCompany.FoundedOn);
                else
                    writer.WriteNull("founded_on");

            if (createLeadRequestCompany.IndustryOption.IsSet)
                if (createLeadRequestCompany.IndustryOption.Value != null)
                    writer.WriteString("industry", createLeadRequestCompany.Industry);
                else
                    writer.WriteNull("industry");

            if (createLeadRequestCompany.LinkedinOption.IsSet)
                if (createLeadRequestCompany.LinkedinOption.Value != null)
                    writer.WriteString("linkedin", createLeadRequestCompany.Linkedin);
                else
                    writer.WriteNull("linkedin");

            if (createLeadRequestCompany.LocationOption.IsSet)
                if (createLeadRequestCompany.LocationOption.Value != null)
                    writer.WriteString("location", createLeadRequestCompany.Location);
                else
                    writer.WriteNull("location");

            if (createLeadRequestCompany.NameOption.IsSet)
                if (createLeadRequestCompany.NameOption.Value != null)
                    writer.WriteString("name", createLeadRequestCompany.Name);
                else
                    writer.WriteNull("name");

            if (createLeadRequestCompany.NumberOfEmployeesOption.IsSet)
                if (createLeadRequestCompany.NumberOfEmployeesOption.Value != null)
                    writer.WriteNumber("number_of_employees", createLeadRequestCompany.NumberOfEmployeesOption.Value!.Value);
                else
                    writer.WriteNull("number_of_employees");

            if (createLeadRequestCompany.StockOption.IsSet)
                if (createLeadRequestCompany.StockOption.Value != null)
                    writer.WriteString("stock", createLeadRequestCompany.Stock);
                else
                    writer.WriteNull("stock");

            if (createLeadRequestCompany.TwitterOption.IsSet)
                if (createLeadRequestCompany.TwitterOption.Value != null)
                    writer.WriteString("twitter", createLeadRequestCompany.Twitter);
                else
                    writer.WriteNull("twitter");

            if (createLeadRequestCompany.TypeOption.IsSet)
                if (createLeadRequestCompany.TypeOption.Value != null)
                    writer.WriteString("type", createLeadRequestCompany.Type);
                else
                    writer.WriteNull("type");

            if (createLeadRequestCompany.WebsiteOption.IsSet)
                if (createLeadRequestCompany.WebsiteOption.Value != null)
                    writer.WriteString("website", createLeadRequestCompany.Website);
                else
                    writer.WriteNull("website");
        }
    }
}
