// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// CrmSyncConfigurationHubspot
    /// </summary>
    public partial class CrmSyncConfigurationHubspot : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CrmSyncConfigurationHubspot" /> class.
        /// </summary>
        /// <param name="deal">deal</param>
        /// <param name="contactOwnerId">contactOwnerId</param>
        [JsonConstructor]
        public CrmSyncConfigurationHubspot(CrmSyncConfigurationHubspotDeal deal, string? contactOwnerId = default)
        {
            Deal = deal;
            ContactOwnerId = contactOwnerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Deal
        /// </summary>
        [JsonPropertyName("deal")]
        public CrmSyncConfigurationHubspotDeal Deal { get; set; }

        /// <summary>
        /// Gets or Sets ContactOwnerId
        /// </summary>
        [JsonPropertyName("contactOwnerId")]
        public string? ContactOwnerId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CrmSyncConfigurationHubspot {\n");
            sb.Append("  Deal: ").Append(Deal).Append("\n");
            sb.Append("  ContactOwnerId: ").Append(ContactOwnerId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CrmSyncConfigurationHubspot" />
    /// </summary>
    public partial class CrmSyncConfigurationHubspotJsonConverter : JsonConverter<CrmSyncConfigurationHubspot>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CrmSyncConfigurationHubspotJsonConverter" /> class.
        /// </summary>
        public CrmSyncConfigurationHubspotJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CrmSyncConfigurationHubspot" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CrmSyncConfigurationHubspot Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CrmSyncConfigurationHubspotDeal?> deal = default;
            Option<string?> contactOwnerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "deal":
                            deal = new Option<CrmSyncConfigurationHubspotDeal?>(JsonSerializer.Deserialize<CrmSyncConfigurationHubspotDeal>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "contactOwnerId":
                            contactOwnerId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!deal.IsSet)
                throw new ArgumentException("Property is required for class CrmSyncConfigurationHubspot.", nameof(deal));

            if (!contactOwnerId.IsSet)
                throw new ArgumentException("Property is required for class CrmSyncConfigurationHubspot.", nameof(contactOwnerId));

            if (deal.IsSet && deal.Value == null)
                throw new ArgumentNullException(nameof(deal), "Property is not nullable for class CrmSyncConfigurationHubspot.");

            var reaconModelResult = new CrmSyncConfigurationHubspot(deal.Value!, contactOwnerId.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="CrmSyncConfigurationHubspot" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="crmSyncConfigurationHubspot"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CrmSyncConfigurationHubspot crmSyncConfigurationHubspot, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, crmSyncConfigurationHubspot, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CrmSyncConfigurationHubspot" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="crmSyncConfigurationHubspot"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CrmSyncConfigurationHubspot crmSyncConfigurationHubspot, JsonSerializerOptions jsonSerializerOptions)
        {
            if (crmSyncConfigurationHubspot.Deal == null)
                throw new ArgumentNullException(nameof(crmSyncConfigurationHubspot.Deal), "Property is required for class CrmSyncConfigurationHubspot.");

            writer.WritePropertyName("deal");
            JsonSerializer.Serialize(writer, crmSyncConfigurationHubspot.Deal, jsonSerializerOptions);
            if (crmSyncConfigurationHubspot.ContactOwnerId != null)
                writer.WriteString("contactOwnerId", crmSyncConfigurationHubspot.ContactOwnerId);
            else
                writer.WriteNull("contactOwnerId");

            foreach (var property in crmSyncConfigurationHubspot.AdditionalProperties)
            {
                if (property.Key == "deal" || property.Key == "contactOwnerId") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
