// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// DomainCompanyContextCompany
    /// </summary>
    public partial class DomainCompanyContextCompany : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainCompanyContextCompany" /> class.
        /// </summary>
        /// <param name="domain">domain</param>
        /// <param name="id">id</param>
        /// <param name="jobs">jobs</param>
        /// <param name="name">name</param>
        /// <param name="sources">sources</param>
        /// <param name="specialties">specialties</param>
        /// <param name="address">address</param>
        /// <param name="companyType">companyType</param>
        /// <param name="description">description</param>
        /// <param name="employeeCount">employeeCount</param>
        /// <param name="employeeRange">employeeRange</param>
        /// <param name="followerCount">followerCount</param>
        /// <param name="foundedOn">foundedOn</param>
        /// <param name="headquarters">headquarters</param>
        /// <param name="industry">industry</param>
        /// <param name="linkedin">linkedin</param>
        /// <param name="stockSymbol">stockSymbol</param>
        /// <param name="tagline">tagline</param>
        /// <param name="website">website</param>
        [JsonConstructor]
        public DomainCompanyContextCompany(string domain, string id, List<CompanyContextJob> jobs, string name, List<CompanyContextSource> sources, List<string> specialties, CompanyContextAddress? address = default, string? companyType = default, string? description = default, int? employeeCount = default, string? employeeRange = default, int? followerCount = default, string? foundedOn = default, string? headquarters = default, string? industry = default, string? linkedin = default, string? stockSymbol = default, string? tagline = default, string? website = default)
        {
            Domain = domain;
            Id = id;
            Jobs = jobs;
            Name = name;
            Sources = sources;
            Specialties = specialties;
            Address = address;
            CompanyType = companyType;
            Description = description;
            EmployeeCount = employeeCount;
            EmployeeRange = employeeRange;
            FollowerCount = followerCount;
            FoundedOn = foundedOn;
            Headquarters = headquarters;
            Industry = industry;
            Linkedin = linkedin;
            StockSymbol = stockSymbol;
            Tagline = tagline;
            Website = website;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Jobs
        /// </summary>
        [JsonPropertyName("jobs")]
        public List<CompanyContextJob> Jobs { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Sources
        /// </summary>
        [JsonPropertyName("sources")]
        public List<CompanyContextSource> Sources { get; set; }

        /// <summary>
        /// Gets or Sets Specialties
        /// </summary>
        [JsonPropertyName("specialties")]
        public List<string> Specialties { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public CompanyContextAddress? Address { get; set; }

        /// <summary>
        /// Gets or Sets CompanyType
        /// </summary>
        [JsonPropertyName("companyType")]
        public string? CompanyType { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets EmployeeCount
        /// </summary>
        [JsonPropertyName("employeeCount")]
        public int? EmployeeCount { get; set; }

        /// <summary>
        /// Gets or Sets EmployeeRange
        /// </summary>
        [JsonPropertyName("employeeRange")]
        public string? EmployeeRange { get; set; }

        /// <summary>
        /// Gets or Sets FollowerCount
        /// </summary>
        [JsonPropertyName("followerCount")]
        public int? FollowerCount { get; set; }

        /// <summary>
        /// Gets or Sets FoundedOn
        /// </summary>
        [JsonPropertyName("foundedOn")]
        public string? FoundedOn { get; set; }

        /// <summary>
        /// Gets or Sets Headquarters
        /// </summary>
        [JsonPropertyName("headquarters")]
        public string? Headquarters { get; set; }

        /// <summary>
        /// Gets or Sets Industry
        /// </summary>
        [JsonPropertyName("industry")]
        public string? Industry { get; set; }

        /// <summary>
        /// Gets or Sets Linkedin
        /// </summary>
        [JsonPropertyName("linkedin")]
        public string? Linkedin { get; set; }

        /// <summary>
        /// Gets or Sets StockSymbol
        /// </summary>
        [JsonPropertyName("stockSymbol")]
        public string? StockSymbol { get; set; }

        /// <summary>
        /// Gets or Sets Tagline
        /// </summary>
        [JsonPropertyName("tagline")]
        public string? Tagline { get; set; }

        /// <summary>
        /// Gets or Sets Website
        /// </summary>
        [JsonPropertyName("website")]
        public string? Website { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DomainCompanyContextCompany {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Jobs: ").Append(Jobs).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Sources: ").Append(Sources).Append("\n");
            sb.Append("  Specialties: ").Append(Specialties).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  CompanyType: ").Append(CompanyType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EmployeeCount: ").Append(EmployeeCount).Append("\n");
            sb.Append("  EmployeeRange: ").Append(EmployeeRange).Append("\n");
            sb.Append("  FollowerCount: ").Append(FollowerCount).Append("\n");
            sb.Append("  FoundedOn: ").Append(FoundedOn).Append("\n");
            sb.Append("  Headquarters: ").Append(Headquarters).Append("\n");
            sb.Append("  Industry: ").Append(Industry).Append("\n");
            sb.Append("  Linkedin: ").Append(Linkedin).Append("\n");
            sb.Append("  StockSymbol: ").Append(StockSymbol).Append("\n");
            sb.Append("  Tagline: ").Append(Tagline).Append("\n");
            sb.Append("  Website: ").Append(Website).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DomainCompanyContextCompany" />
    /// </summary>
    public partial class DomainCompanyContextCompanyJsonConverter : JsonConverter<DomainCompanyContextCompany>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainCompanyContextCompanyJsonConverter" /> class.
        /// </summary>
        public DomainCompanyContextCompanyJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DomainCompanyContextCompany" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DomainCompanyContextCompany Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> domain = default;
            Option<string?> id = default;
            Option<List<CompanyContextJob>?> jobs = default;
            Option<string?> name = default;
            Option<List<CompanyContextSource>?> sources = default;
            Option<List<string>?> specialties = default;
            Option<CompanyContextAddress?> address = default;
            Option<string?> companyType = default;
            Option<string?> description = default;
            Option<int?> employeeCount = default;
            Option<string?> employeeRange = default;
            Option<int?> followerCount = default;
            Option<string?> foundedOn = default;
            Option<string?> headquarters = default;
            Option<string?> industry = default;
            Option<string?> linkedin = default;
            Option<string?> stockSymbol = default;
            Option<string?> tagline = default;
            Option<string?> website = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "domain":
                            domain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "jobs":
                            jobs = new Option<List<CompanyContextJob>?>(JsonSerializer.Deserialize<List<CompanyContextJob>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sources":
                            sources = new Option<List<CompanyContextSource>?>(JsonSerializer.Deserialize<List<CompanyContextSource>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "specialties":
                            specialties = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "address":
                            address = new Option<CompanyContextAddress?>(JsonSerializer.Deserialize<CompanyContextAddress>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "companyType":
                            companyType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "employeeCount":
                            employeeCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "employeeRange":
                            employeeRange = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "followerCount":
                            followerCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "foundedOn":
                            foundedOn = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "headquarters":
                            headquarters = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "industry":
                            industry = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "linkedin":
                            linkedin = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "stockSymbol":
                            stockSymbol = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "tagline":
                            tagline = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "website":
                            website = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!domain.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(domain));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(id));

            if (!jobs.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(jobs));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(name));

            if (!sources.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(sources));

            if (!specialties.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(specialties));

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(address));

            if (!companyType.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(companyType));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(description));

            if (!employeeCount.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(employeeCount));

            if (!employeeRange.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(employeeRange));

            if (!followerCount.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(followerCount));

            if (!foundedOn.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(foundedOn));

            if (!headquarters.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(headquarters));

            if (!industry.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(industry));

            if (!linkedin.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(linkedin));

            if (!stockSymbol.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(stockSymbol));

            if (!tagline.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(tagline));

            if (!website.IsSet)
                throw new ArgumentException("Property is required for class DomainCompanyContextCompany.", nameof(website));

            if (domain.IsSet && domain.Value == null)
                throw new ArgumentNullException(nameof(domain), "Property is not nullable for class DomainCompanyContextCompany.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class DomainCompanyContextCompany.");

            if (jobs.IsSet && jobs.Value == null)
                throw new ArgumentNullException(nameof(jobs), "Property is not nullable for class DomainCompanyContextCompany.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class DomainCompanyContextCompany.");

            if (sources.IsSet && sources.Value == null)
                throw new ArgumentNullException(nameof(sources), "Property is not nullable for class DomainCompanyContextCompany.");

            if (specialties.IsSet && specialties.Value == null)
                throw new ArgumentNullException(nameof(specialties), "Property is not nullable for class DomainCompanyContextCompany.");

            var reaconModelResult = new DomainCompanyContextCompany(domain.Value!, id.Value!, jobs.Value!, name.Value!, sources.Value!, specialties.Value!, address.Value!, companyType.Value!, description.Value!, employeeCount.Value!, employeeRange.Value!, followerCount.Value!, foundedOn.Value!, headquarters.Value!, industry.Value!, linkedin.Value!, stockSymbol.Value!, tagline.Value!, website.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="DomainCompanyContextCompany" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="domainCompanyContextCompany"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DomainCompanyContextCompany domainCompanyContextCompany, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, domainCompanyContextCompany, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DomainCompanyContextCompany" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="domainCompanyContextCompany"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DomainCompanyContextCompany domainCompanyContextCompany, JsonSerializerOptions jsonSerializerOptions)
        {
            if (domainCompanyContextCompany.Domain == null)
                throw new ArgumentNullException(nameof(domainCompanyContextCompany.Domain), "Property is required for class DomainCompanyContextCompany.");

            if (domainCompanyContextCompany.Id == null)
                throw new ArgumentNullException(nameof(domainCompanyContextCompany.Id), "Property is required for class DomainCompanyContextCompany.");

            if (domainCompanyContextCompany.Jobs == null)
                throw new ArgumentNullException(nameof(domainCompanyContextCompany.Jobs), "Property is required for class DomainCompanyContextCompany.");

            if (domainCompanyContextCompany.Name == null)
                throw new ArgumentNullException(nameof(domainCompanyContextCompany.Name), "Property is required for class DomainCompanyContextCompany.");

            if (domainCompanyContextCompany.Sources == null)
                throw new ArgumentNullException(nameof(domainCompanyContextCompany.Sources), "Property is required for class DomainCompanyContextCompany.");

            if (domainCompanyContextCompany.Specialties == null)
                throw new ArgumentNullException(nameof(domainCompanyContextCompany.Specialties), "Property is required for class DomainCompanyContextCompany.");

            writer.WriteString("domain", domainCompanyContextCompany.Domain);

            writer.WriteString("id", domainCompanyContextCompany.Id);

            writer.WritePropertyName("jobs");
            JsonSerializer.Serialize(writer, domainCompanyContextCompany.Jobs, jsonSerializerOptions);
            writer.WriteString("name", domainCompanyContextCompany.Name);

            writer.WritePropertyName("sources");
            JsonSerializer.Serialize(writer, domainCompanyContextCompany.Sources, jsonSerializerOptions);
            writer.WritePropertyName("specialties");
            JsonSerializer.Serialize(writer, domainCompanyContextCompany.Specialties, jsonSerializerOptions);
            if (domainCompanyContextCompany.Address != null)
            {
                writer.WritePropertyName("address");
                JsonSerializer.Serialize(writer, domainCompanyContextCompany.Address, jsonSerializerOptions);
            }
            else
                writer.WriteNull("address");
            if (domainCompanyContextCompany.CompanyType != null)
                writer.WriteString("companyType", domainCompanyContextCompany.CompanyType);
            else
                writer.WriteNull("companyType");

            if (domainCompanyContextCompany.Description != null)
                writer.WriteString("description", domainCompanyContextCompany.Description);
            else
                writer.WriteNull("description");

            if (domainCompanyContextCompany.EmployeeCount != null)
                writer.WriteNumber("employeeCount", domainCompanyContextCompany.EmployeeCount.Value);
            else
                writer.WriteNull("employeeCount");

            if (domainCompanyContextCompany.EmployeeRange != null)
                writer.WriteString("employeeRange", domainCompanyContextCompany.EmployeeRange);
            else
                writer.WriteNull("employeeRange");

            if (domainCompanyContextCompany.FollowerCount != null)
                writer.WriteNumber("followerCount", domainCompanyContextCompany.FollowerCount.Value);
            else
                writer.WriteNull("followerCount");

            if (domainCompanyContextCompany.FoundedOn != null)
                writer.WriteString("foundedOn", domainCompanyContextCompany.FoundedOn);
            else
                writer.WriteNull("foundedOn");

            if (domainCompanyContextCompany.Headquarters != null)
                writer.WriteString("headquarters", domainCompanyContextCompany.Headquarters);
            else
                writer.WriteNull("headquarters");

            if (domainCompanyContextCompany.Industry != null)
                writer.WriteString("industry", domainCompanyContextCompany.Industry);
            else
                writer.WriteNull("industry");

            if (domainCompanyContextCompany.Linkedin != null)
                writer.WriteString("linkedin", domainCompanyContextCompany.Linkedin);
            else
                writer.WriteNull("linkedin");

            if (domainCompanyContextCompany.StockSymbol != null)
                writer.WriteString("stockSymbol", domainCompanyContextCompany.StockSymbol);
            else
                writer.WriteNull("stockSymbol");

            if (domainCompanyContextCompany.Tagline != null)
                writer.WriteString("tagline", domainCompanyContextCompany.Tagline);
            else
                writer.WriteNull("tagline");

            if (domainCompanyContextCompany.Website != null)
                writer.WriteString("website", domainCompanyContextCompany.Website);
            else
                writer.WriteNull("website");

            foreach (var property in domainCompanyContextCompany.AdditionalProperties)
            {
                if (property.Key == "domain" || property.Key == "id" || property.Key == "jobs" || property.Key == "name" || property.Key == "sources" || property.Key == "specialties" || property.Key == "address" || property.Key == "companyType" || property.Key == "description" || property.Key == "employeeCount" || property.Key == "employeeRange" || property.Key == "followerCount" || property.Key == "foundedOn" || property.Key == "headquarters" || property.Key == "industry" || property.Key == "linkedin" || property.Key == "stockSymbol" || property.Key == "tagline" || property.Key == "website") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
