// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// GoogleSheetInspectionResponse
    /// </summary>
    public partial class GoogleSheetInspectionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleSheetInspectionResponse" /> class.
        /// </summary>
        /// <param name="inspection">inspection</param>
        [JsonConstructor]
        public GoogleSheetInspectionResponse(GoogleSheetInspectionResponseInspection inspection)
        {
            Inspection = inspection;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Inspection
        /// </summary>
        [JsonPropertyName("inspection")]
        public GoogleSheetInspectionResponseInspection Inspection { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GoogleSheetInspectionResponse {\n");
            sb.Append("  Inspection: ").Append(Inspection).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GoogleSheetInspectionResponse" />
    /// </summary>
    public partial class GoogleSheetInspectionResponseJsonConverter : JsonConverter<GoogleSheetInspectionResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleSheetInspectionResponseJsonConverter" /> class.
        /// </summary>
        public GoogleSheetInspectionResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GoogleSheetInspectionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GoogleSheetInspectionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GoogleSheetInspectionResponseInspection?> inspection = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "inspection":
                            inspection = new Option<GoogleSheetInspectionResponseInspection?>(JsonSerializer.Deserialize<GoogleSheetInspectionResponseInspection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!inspection.IsSet)
                throw new ArgumentException("Property is required for class GoogleSheetInspectionResponse.", nameof(inspection));

            if (inspection.IsSet && inspection.Value == null)
                throw new ArgumentNullException(nameof(inspection), "Property is not nullable for class GoogleSheetInspectionResponse.");

            var reaconModelResult = new GoogleSheetInspectionResponse(inspection.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="GoogleSheetInspectionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="googleSheetInspectionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GoogleSheetInspectionResponse googleSheetInspectionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, googleSheetInspectionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GoogleSheetInspectionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="googleSheetInspectionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GoogleSheetInspectionResponse googleSheetInspectionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (googleSheetInspectionResponse.Inspection == null)
                throw new ArgumentNullException(nameof(googleSheetInspectionResponse.Inspection), "Property is required for class GoogleSheetInspectionResponse.");

            writer.WritePropertyName("inspection");
            JsonSerializer.Serialize(writer, googleSheetInspectionResponse.Inspection, jsonSerializerOptions);

            foreach (var property in googleSheetInspectionResponse.AdditionalProperties)
            {
                if (property.Key == "inspection") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
