// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// InsightMentionErrorEvent
    /// </summary>
    public partial class InsightMentionErrorEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InsightMentionErrorEvent" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="error">error</param>
        /// <param name="kind">Known values: mention_error. Clients preserve future values.</param>
        /// <param name="sourceUrl">sourceUrl</param>
        [JsonConstructor]
        public InsightMentionErrorEvent(string email, string error, string kind, string sourceUrl)
        {
            Email = email;
            Error = error;
            Kind = kind;
            SourceUrl = sourceUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public string Error { get; set; }

        /// <summary>
        /// Known values: mention_error. Clients preserve future values.
        /// </summary>
        /// <value>Known values: mention_error. Clients preserve future values.</value>
        [JsonPropertyName("kind")]
        public string Kind { get; set; }

        /// <summary>
        /// Gets or Sets SourceUrl
        /// </summary>
        [JsonPropertyName("sourceUrl")]
        public string SourceUrl { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InsightMentionErrorEvent {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  SourceUrl: ").Append(SourceUrl).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InsightMentionErrorEvent" />
    /// </summary>
    public partial class InsightMentionErrorEventJsonConverter : JsonConverter<InsightMentionErrorEvent>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="InsightMentionErrorEventJsonConverter" /> class.
        /// </summary>
        public InsightMentionErrorEventJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="InsightMentionErrorEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InsightMentionErrorEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<string?> error = default;
            Option<string?> kind = default;
            Option<string?> sourceUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "kind":
                            kind = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceUrl":
                            sourceUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class InsightMentionErrorEvent.", nameof(email));

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class InsightMentionErrorEvent.", nameof(error));

            if (!kind.IsSet)
                throw new ArgumentException("Property is required for class InsightMentionErrorEvent.", nameof(kind));

            if (!sourceUrl.IsSet)
                throw new ArgumentException("Property is required for class InsightMentionErrorEvent.", nameof(sourceUrl));

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class InsightMentionErrorEvent.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class InsightMentionErrorEvent.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class InsightMentionErrorEvent.");

            if (sourceUrl.IsSet && sourceUrl.Value == null)
                throw new ArgumentNullException(nameof(sourceUrl), "Property is not nullable for class InsightMentionErrorEvent.");

            var reaconModelResult = new InsightMentionErrorEvent(email.Value!, error.Value!, kind.Value!, sourceUrl.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="InsightMentionErrorEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="insightMentionErrorEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InsightMentionErrorEvent insightMentionErrorEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, insightMentionErrorEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InsightMentionErrorEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="insightMentionErrorEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InsightMentionErrorEvent insightMentionErrorEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            if (insightMentionErrorEvent.Email == null)
                throw new ArgumentNullException(nameof(insightMentionErrorEvent.Email), "Property is required for class InsightMentionErrorEvent.");

            if (insightMentionErrorEvent.Error == null)
                throw new ArgumentNullException(nameof(insightMentionErrorEvent.Error), "Property is required for class InsightMentionErrorEvent.");

            if (insightMentionErrorEvent.Kind == null)
                throw new ArgumentNullException(nameof(insightMentionErrorEvent.Kind), "Property is required for class InsightMentionErrorEvent.");

            if (insightMentionErrorEvent.SourceUrl == null)
                throw new ArgumentNullException(nameof(insightMentionErrorEvent.SourceUrl), "Property is required for class InsightMentionErrorEvent.");

            writer.WriteString("email", insightMentionErrorEvent.Email);

            writer.WriteString("error", insightMentionErrorEvent.Error);

            writer.WriteString("kind", insightMentionErrorEvent.Kind);

            writer.WriteString("sourceUrl", insightMentionErrorEvent.SourceUrl);

            foreach (var property in insightMentionErrorEvent.AdditionalProperties)
            {
                if (property.Key == "email" || property.Key == "error" || property.Key == "kind" || property.Key == "sourceUrl") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
