// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// IntegrationJobCounters
    /// </summary>
    public partial class IntegrationJobCounters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationJobCounters" /> class.
        /// </summary>
        /// <param name="failed">failed</param>
        /// <param name="processed">processed</param>
        /// <param name="skipped">skipped</param>
        /// <param name="succeeded">succeeded</param>
        [JsonConstructor]
        public IntegrationJobCounters(int failed, int processed, int skipped, int succeeded)
        {
            Failed = failed;
            Processed = processed;
            Skipped = skipped;
            Succeeded = succeeded;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Failed
        /// </summary>
        [JsonPropertyName("failed")]
        public int Failed { get; set; }

        /// <summary>
        /// Gets or Sets Processed
        /// </summary>
        [JsonPropertyName("processed")]
        public int Processed { get; set; }

        /// <summary>
        /// Gets or Sets Skipped
        /// </summary>
        [JsonPropertyName("skipped")]
        public int Skipped { get; set; }

        /// <summary>
        /// Gets or Sets Succeeded
        /// </summary>
        [JsonPropertyName("succeeded")]
        public int Succeeded { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IntegrationJobCounters {\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("  Processed: ").Append(Processed).Append("\n");
            sb.Append("  Skipped: ").Append(Skipped).Append("\n");
            sb.Append("  Succeeded: ").Append(Succeeded).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Failed (int) minimum
            if (this.Failed < (int)0)
            {
                yield return new ValidationResult("Invalid value for Failed, must be a value greater than or equal to 0.", new [] { "Failed" });
            }

            // Processed (int) minimum
            if (this.Processed < (int)0)
            {
                yield return new ValidationResult("Invalid value for Processed, must be a value greater than or equal to 0.", new [] { "Processed" });
            }

            // Skipped (int) minimum
            if (this.Skipped < (int)0)
            {
                yield return new ValidationResult("Invalid value for Skipped, must be a value greater than or equal to 0.", new [] { "Skipped" });
            }

            // Succeeded (int) minimum
            if (this.Succeeded < (int)0)
            {
                yield return new ValidationResult("Invalid value for Succeeded, must be a value greater than or equal to 0.", new [] { "Succeeded" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IntegrationJobCounters" />
    /// </summary>
    public partial class IntegrationJobCountersJsonConverter : JsonConverter<IntegrationJobCounters>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationJobCountersJsonConverter" /> class.
        /// </summary>
        public IntegrationJobCountersJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="IntegrationJobCounters" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IntegrationJobCounters Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> failed = default;
            Option<int?> processed = default;
            Option<int?> skipped = default;
            Option<int?> succeeded = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "failed":
                            failed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "processed":
                            processed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "skipped":
                            skipped = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "succeeded":
                            succeeded = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!failed.IsSet)
                throw new ArgumentException("Property is required for class IntegrationJobCounters.", nameof(failed));

            if (!processed.IsSet)
                throw new ArgumentException("Property is required for class IntegrationJobCounters.", nameof(processed));

            if (!skipped.IsSet)
                throw new ArgumentException("Property is required for class IntegrationJobCounters.", nameof(skipped));

            if (!succeeded.IsSet)
                throw new ArgumentException("Property is required for class IntegrationJobCounters.", nameof(succeeded));

            if (failed.IsSet && failed.Value == null)
                throw new ArgumentNullException(nameof(failed), "Property is not nullable for class IntegrationJobCounters.");

            if (processed.IsSet && processed.Value == null)
                throw new ArgumentNullException(nameof(processed), "Property is not nullable for class IntegrationJobCounters.");

            if (skipped.IsSet && skipped.Value == null)
                throw new ArgumentNullException(nameof(skipped), "Property is not nullable for class IntegrationJobCounters.");

            if (succeeded.IsSet && succeeded.Value == null)
                throw new ArgumentNullException(nameof(succeeded), "Property is not nullable for class IntegrationJobCounters.");

            var reaconModelResult = new IntegrationJobCounters(failed.Value!.Value!, processed.Value!.Value!, skipped.Value!.Value!, succeeded.Value!.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="IntegrationJobCounters" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="integrationJobCounters"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IntegrationJobCounters integrationJobCounters, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, integrationJobCounters, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IntegrationJobCounters" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="integrationJobCounters"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IntegrationJobCounters integrationJobCounters, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("failed", integrationJobCounters.Failed);

            writer.WriteNumber("processed", integrationJobCounters.Processed);

            writer.WriteNumber("skipped", integrationJobCounters.Skipped);

            writer.WriteNumber("succeeded", integrationJobCounters.Succeeded);

            foreach (var property in integrationJobCounters.AdditionalProperties)
            {
                if (property.Key == "failed" || property.Key == "processed" || property.Key == "skipped" || property.Key == "succeeded") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
