// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailGetChannelsResponse200Execution
    /// </summary>
    public partial class MailGetChannelsResponse200Execution : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailGetChannelsResponse200Execution" /> class.
        /// </summary>
        /// <param name="cadence">cadence</param>
        /// <param name="inbound">inbound</param>
        /// <param name="outbound">outbound</param>
        [JsonConstructor]
        public MailGetChannelsResponse200Execution(bool cadence, bool inbound, bool outbound)
        {
            Cadence = cadence;
            Inbound = inbound;
            Outbound = outbound;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Cadence
        /// </summary>
        [JsonPropertyName("cadence")]
        public bool Cadence { get; set; }

        /// <summary>
        /// Gets or Sets Inbound
        /// </summary>
        [JsonPropertyName("inbound")]
        public bool Inbound { get; set; }

        /// <summary>
        /// Gets or Sets Outbound
        /// </summary>
        [JsonPropertyName("outbound")]
        public bool Outbound { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailGetChannelsResponse200Execution {\n");
            sb.Append("  Cadence: ").Append(Cadence).Append("\n");
            sb.Append("  Inbound: ").Append(Inbound).Append("\n");
            sb.Append("  Outbound: ").Append(Outbound).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailGetChannelsResponse200Execution" />
    /// </summary>
    public partial class MailGetChannelsResponse200ExecutionJsonConverter : JsonConverter<MailGetChannelsResponse200Execution>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailGetChannelsResponse200ExecutionJsonConverter" /> class.
        /// </summary>
        public MailGetChannelsResponse200ExecutionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailGetChannelsResponse200Execution" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailGetChannelsResponse200Execution Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> cadence = default;
            Option<bool?> inbound = default;
            Option<bool?> outbound = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "cadence":
                            cadence = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "inbound":
                            inbound = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "outbound":
                            outbound = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!cadence.IsSet)
                throw new ArgumentException("Property is required for class MailGetChannelsResponse200Execution.", nameof(cadence));

            if (!inbound.IsSet)
                throw new ArgumentException("Property is required for class MailGetChannelsResponse200Execution.", nameof(inbound));

            if (!outbound.IsSet)
                throw new ArgumentException("Property is required for class MailGetChannelsResponse200Execution.", nameof(outbound));

            if (cadence.IsSet && cadence.Value == null)
                throw new ArgumentNullException(nameof(cadence), "Property is not nullable for class MailGetChannelsResponse200Execution.");

            if (inbound.IsSet && inbound.Value == null)
                throw new ArgumentNullException(nameof(inbound), "Property is not nullable for class MailGetChannelsResponse200Execution.");

            if (outbound.IsSet && outbound.Value == null)
                throw new ArgumentNullException(nameof(outbound), "Property is not nullable for class MailGetChannelsResponse200Execution.");

            var reaconModelResult = new MailGetChannelsResponse200Execution(cadence.Value!.Value!, inbound.Value!.Value!, outbound.Value!.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailGetChannelsResponse200Execution" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailGetChannelsResponse200Execution"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailGetChannelsResponse200Execution mailGetChannelsResponse200Execution, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailGetChannelsResponse200Execution, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailGetChannelsResponse200Execution" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailGetChannelsResponse200Execution"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailGetChannelsResponse200Execution mailGetChannelsResponse200Execution, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("cadence", mailGetChannelsResponse200Execution.Cadence);

            writer.WriteBoolean("inbound", mailGetChannelsResponse200Execution.Inbound);

            writer.WriteBoolean("outbound", mailGetChannelsResponse200Execution.Outbound);

            foreach (var property in mailGetChannelsResponse200Execution.AdditionalProperties)
            {
                if (property.Key == "cadence" || property.Key == "inbound" || property.Key == "outbound") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
