// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPostCrmContactsBatchResponse200
    /// </summary>
    public partial class MailPostCrmContactsBatchResponse200 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostCrmContactsBatchResponse200" /> class.
        /// </summary>
        /// <param name="results">results</param>
        [JsonConstructor]
        public MailPostCrmContactsBatchResponse200(List<MailContactRecord> results)
        {
            Results = results;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [JsonPropertyName("results")]
        public List<MailContactRecord> Results { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPostCrmContactsBatchResponse200 {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPostCrmContactsBatchResponse200" />
    /// </summary>
    public partial class MailPostCrmContactsBatchResponse200JsonConverter : JsonConverter<MailPostCrmContactsBatchResponse200>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostCrmContactsBatchResponse200JsonConverter" /> class.
        /// </summary>
        public MailPostCrmContactsBatchResponse200JsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPostCrmContactsBatchResponse200" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPostCrmContactsBatchResponse200 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<MailContactRecord>?> results = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "results":
                            results = new Option<List<MailContactRecord>?>(JsonSerializer.Deserialize<List<MailContactRecord>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!results.IsSet)
                throw new ArgumentException("Property is required for class MailPostCrmContactsBatchResponse200.", nameof(results));

            if (results.IsSet && results.Value == null)
                throw new ArgumentNullException(nameof(results), "Property is not nullable for class MailPostCrmContactsBatchResponse200.");

            var reaconModelResult = new MailPostCrmContactsBatchResponse200(results.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailPostCrmContactsBatchResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostCrmContactsBatchResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPostCrmContactsBatchResponse200 mailPostCrmContactsBatchResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPostCrmContactsBatchResponse200, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPostCrmContactsBatchResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostCrmContactsBatchResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPostCrmContactsBatchResponse200 mailPostCrmContactsBatchResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPostCrmContactsBatchResponse200.Results == null)
                throw new ArgumentNullException(nameof(mailPostCrmContactsBatchResponse200.Results), "Property is required for class MailPostCrmContactsBatchResponse200.");

            writer.WritePropertyName("results");
            JsonSerializer.Serialize(writer, mailPostCrmContactsBatchResponse200.Results, jsonSerializerOptions);

            foreach (var property in mailPostCrmContactsBatchResponse200.AdditionalProperties)
            {
                if (property.Key == "results") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
