// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailSignatureCandidateFields
    /// </summary>
    public partial class MailSignatureCandidateFields : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailSignatureCandidateFields" /> class.
        /// </summary>
        /// <param name="emails">emails</param>
        /// <param name="phones">phones</param>
        /// <param name="socialProfiles">socialProfiles</param>
        /// <param name="websites">websites</param>
        /// <param name="address">address</param>
        /// <param name="company">company</param>
        /// <param name="jobTitle">jobTitle</param>
        /// <param name="personName">personName</param>
        [JsonConstructor]
        public MailSignatureCandidateFields(List<MailEvidenceField> emails, List<MailSignatureCandidateFieldsPhonesInner> phones, List<MailEvidenceField> socialProfiles, List<MailEvidenceField> websites, Option<MailEvidenceField?> address = default, Option<MailEvidenceField?> company = default, Option<MailEvidenceField?> jobTitle = default, Option<MailEvidenceField?> personName = default)
        {
            Emails = emails;
            Phones = phones;
            SocialProfiles = socialProfiles;
            Websites = websites;
            AddressOption = address;
            CompanyOption = company;
            JobTitleOption = jobTitle;
            PersonNameOption = personName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Emails
        /// </summary>
        [JsonPropertyName("emails")]
        public List<MailEvidenceField> Emails { get; set; }

        /// <summary>
        /// Gets or Sets Phones
        /// </summary>
        [JsonPropertyName("phones")]
        public List<MailSignatureCandidateFieldsPhonesInner> Phones { get; set; }

        /// <summary>
        /// Gets or Sets SocialProfiles
        /// </summary>
        [JsonPropertyName("socialProfiles")]
        public List<MailEvidenceField> SocialProfiles { get; set; }

        /// <summary>
        /// Gets or Sets Websites
        /// </summary>
        [JsonPropertyName("websites")]
        public List<MailEvidenceField> Websites { get; set; }

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailEvidenceField?> AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public MailEvidenceField? Address { get { return this.AddressOption.Value; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Company
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailEvidenceField?> CompanyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Company
        /// </summary>
        [JsonPropertyName("company")]
        public MailEvidenceField? Company { get { return this.CompanyOption.Value; } set { this.CompanyOption = new(value); } }

        /// <summary>
        /// Used to track the state of JobTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailEvidenceField?> JobTitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets JobTitle
        /// </summary>
        [JsonPropertyName("jobTitle")]
        public MailEvidenceField? JobTitle { get { return this.JobTitleOption.Value; } set { this.JobTitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of PersonName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailEvidenceField?> PersonNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets PersonName
        /// </summary>
        [JsonPropertyName("personName")]
        public MailEvidenceField? PersonName { get { return this.PersonNameOption.Value; } set { this.PersonNameOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailSignatureCandidateFields {\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("  Phones: ").Append(Phones).Append("\n");
            sb.Append("  SocialProfiles: ").Append(SocialProfiles).Append("\n");
            sb.Append("  Websites: ").Append(Websites).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  JobTitle: ").Append(JobTitle).Append("\n");
            sb.Append("  PersonName: ").Append(PersonName).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailSignatureCandidateFields" />
    /// </summary>
    public partial class MailSignatureCandidateFieldsJsonConverter : JsonConverter<MailSignatureCandidateFields>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailSignatureCandidateFieldsJsonConverter" /> class.
        /// </summary>
        public MailSignatureCandidateFieldsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailSignatureCandidateFields" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailSignatureCandidateFields Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<MailEvidenceField>?> emails = default;
            Option<List<MailSignatureCandidateFieldsPhonesInner>?> phones = default;
            Option<List<MailEvidenceField>?> socialProfiles = default;
            Option<List<MailEvidenceField>?> websites = default;
            Option<MailEvidenceField?> address = default;
            Option<MailEvidenceField?> company = default;
            Option<MailEvidenceField?> jobTitle = default;
            Option<MailEvidenceField?> personName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "emails":
                            emails = new Option<List<MailEvidenceField>?>(JsonSerializer.Deserialize<List<MailEvidenceField>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "phones":
                            phones = new Option<List<MailSignatureCandidateFieldsPhonesInner>?>(JsonSerializer.Deserialize<List<MailSignatureCandidateFieldsPhonesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "socialProfiles":
                            socialProfiles = new Option<List<MailEvidenceField>?>(JsonSerializer.Deserialize<List<MailEvidenceField>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "websites":
                            websites = new Option<List<MailEvidenceField>?>(JsonSerializer.Deserialize<List<MailEvidenceField>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "address":
                            address = new Option<MailEvidenceField?>(JsonSerializer.Deserialize<MailEvidenceField>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "company":
                            company = new Option<MailEvidenceField?>(JsonSerializer.Deserialize<MailEvidenceField>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "jobTitle":
                            jobTitle = new Option<MailEvidenceField?>(JsonSerializer.Deserialize<MailEvidenceField>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "personName":
                            personName = new Option<MailEvidenceField?>(JsonSerializer.Deserialize<MailEvidenceField>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!emails.IsSet)
                throw new ArgumentException("Property is required for class MailSignatureCandidateFields.", nameof(emails));

            if (!phones.IsSet)
                throw new ArgumentException("Property is required for class MailSignatureCandidateFields.", nameof(phones));

            if (!socialProfiles.IsSet)
                throw new ArgumentException("Property is required for class MailSignatureCandidateFields.", nameof(socialProfiles));

            if (!websites.IsSet)
                throw new ArgumentException("Property is required for class MailSignatureCandidateFields.", nameof(websites));

            if (emails.IsSet && emails.Value == null)
                throw new ArgumentNullException(nameof(emails), "Property is not nullable for class MailSignatureCandidateFields.");

            if (phones.IsSet && phones.Value == null)
                throw new ArgumentNullException(nameof(phones), "Property is not nullable for class MailSignatureCandidateFields.");

            if (socialProfiles.IsSet && socialProfiles.Value == null)
                throw new ArgumentNullException(nameof(socialProfiles), "Property is not nullable for class MailSignatureCandidateFields.");

            if (websites.IsSet && websites.Value == null)
                throw new ArgumentNullException(nameof(websites), "Property is not nullable for class MailSignatureCandidateFields.");

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class MailSignatureCandidateFields.");

            if (company.IsSet && company.Value == null)
                throw new ArgumentNullException(nameof(company), "Property is not nullable for class MailSignatureCandidateFields.");

            if (jobTitle.IsSet && jobTitle.Value == null)
                throw new ArgumentNullException(nameof(jobTitle), "Property is not nullable for class MailSignatureCandidateFields.");

            if (personName.IsSet && personName.Value == null)
                throw new ArgumentNullException(nameof(personName), "Property is not nullable for class MailSignatureCandidateFields.");

            var reaconModelResult = new MailSignatureCandidateFields(emails.Value!, phones.Value!, socialProfiles.Value!, websites.Value!, address, company, jobTitle, personName);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailSignatureCandidateFields" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailSignatureCandidateFields"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailSignatureCandidateFields mailSignatureCandidateFields, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailSignatureCandidateFields, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailSignatureCandidateFields" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailSignatureCandidateFields"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailSignatureCandidateFields mailSignatureCandidateFields, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailSignatureCandidateFields.Emails == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.Emails), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.Phones == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.Phones), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.SocialProfiles == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.SocialProfiles), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.Websites == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.Websites), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.AddressOption.IsSet && mailSignatureCandidateFields.Address == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.Address), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.CompanyOption.IsSet && mailSignatureCandidateFields.Company == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.Company), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.JobTitleOption.IsSet && mailSignatureCandidateFields.JobTitle == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.JobTitle), "Property is required for class MailSignatureCandidateFields.");

            if (mailSignatureCandidateFields.PersonNameOption.IsSet && mailSignatureCandidateFields.PersonName == null)
                throw new ArgumentNullException(nameof(mailSignatureCandidateFields.PersonName), "Property is required for class MailSignatureCandidateFields.");

            writer.WritePropertyName("emails");
            JsonSerializer.Serialize(writer, mailSignatureCandidateFields.Emails, jsonSerializerOptions);
            writer.WritePropertyName("phones");
            JsonSerializer.Serialize(writer, mailSignatureCandidateFields.Phones, jsonSerializerOptions);
            writer.WritePropertyName("socialProfiles");
            JsonSerializer.Serialize(writer, mailSignatureCandidateFields.SocialProfiles, jsonSerializerOptions);
            writer.WritePropertyName("websites");
            JsonSerializer.Serialize(writer, mailSignatureCandidateFields.Websites, jsonSerializerOptions);
            if (mailSignatureCandidateFields.AddressOption.IsSet)
            {
                writer.WritePropertyName("address");
                JsonSerializer.Serialize(writer, mailSignatureCandidateFields.Address, jsonSerializerOptions);
            }
            if (mailSignatureCandidateFields.CompanyOption.IsSet)
            {
                writer.WritePropertyName("company");
                JsonSerializer.Serialize(writer, mailSignatureCandidateFields.Company, jsonSerializerOptions);
            }
            if (mailSignatureCandidateFields.JobTitleOption.IsSet)
            {
                writer.WritePropertyName("jobTitle");
                JsonSerializer.Serialize(writer, mailSignatureCandidateFields.JobTitle, jsonSerializerOptions);
            }
            if (mailSignatureCandidateFields.PersonNameOption.IsSet)
            {
                writer.WritePropertyName("personName");
                JsonSerializer.Serialize(writer, mailSignatureCandidateFields.PersonName, jsonSerializerOptions);
            }

            foreach (var property in mailSignatureCandidateFields.AdditionalProperties)
            {
                if (property.Key == "emails" || property.Key == "phones" || property.Key == "socialProfiles" || property.Key == "websites" || property.Key == "address" || property.Key == "company" || property.Key == "jobTitle" || property.Key == "personName") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
