// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailCadenceExperimentContext
    /// </summary>
    public partial class MailCadenceExperimentContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailCadenceExperimentContext" /> class.
        /// </summary>
        /// <param name="experimentId">experimentId</param>
        /// <param name="experimentKey">experimentKey</param>
        /// <param name="exposedAt">exposedAt</param>
        /// <param name="revision">revision</param>
        /// <param name="unitId">unitId</param>
        /// <param name="variantId">variantId</param>
        [JsonConstructor]
        public MailCadenceExperimentContext(string experimentId, string experimentKey, DateTimeOffset exposedAt, decimal revision, string unitId, string variantId)
        {
            ExperimentId = experimentId;
            ExperimentKey = experimentKey;
            ExposedAt = exposedAt;
            Revision = revision;
            UnitId = unitId;
            VariantId = variantId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ExperimentId
        /// </summary>
        [JsonPropertyName("experimentId")]
        public string ExperimentId { get; set; }

        /// <summary>
        /// Gets or Sets ExperimentKey
        /// </summary>
        [JsonPropertyName("experimentKey")]
        public string ExperimentKey { get; set; }

        /// <summary>
        /// Gets or Sets ExposedAt
        /// </summary>
        [JsonPropertyName("exposedAt")]
        public DateTimeOffset ExposedAt { get; set; }

        /// <summary>
        /// Gets or Sets Revision
        /// </summary>
        [JsonPropertyName("revision")]
        public decimal Revision { get; set; }

        /// <summary>
        /// Gets or Sets UnitId
        /// </summary>
        [JsonPropertyName("unitId")]
        public string UnitId { get; set; }

        /// <summary>
        /// Gets or Sets VariantId
        /// </summary>
        [JsonPropertyName("variantId")]
        public string VariantId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailCadenceExperimentContext {\n");
            sb.Append("  ExperimentId: ").Append(ExperimentId).Append("\n");
            sb.Append("  ExperimentKey: ").Append(ExperimentKey).Append("\n");
            sb.Append("  ExposedAt: ").Append(ExposedAt).Append("\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("  UnitId: ").Append(UnitId).Append("\n");
            sb.Append("  VariantId: ").Append(VariantId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailCadenceExperimentContext" />
    /// </summary>
    public partial class MailCadenceExperimentContextJsonConverter : JsonConverter<MailCadenceExperimentContext>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailCadenceExperimentContextJsonConverter" /> class.
        /// </summary>
        public MailCadenceExperimentContextJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExposedAt
        /// </summary>
        public string ExposedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MailCadenceExperimentContext" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailCadenceExperimentContext Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> experimentId = default;
            Option<string?> experimentKey = default;
            Option<DateTimeOffset?> exposedAt = default;
            Option<decimal?> revision = default;
            Option<string?> unitId = default;
            Option<string?> variantId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "experimentId":
                            experimentId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "experimentKey":
                            experimentKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "exposedAt":
                            exposedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "revision":
                            revision = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "unitId":
                            unitId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "variantId":
                            variantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!experimentId.IsSet)
                throw new ArgumentException("Property is required for class MailCadenceExperimentContext.", nameof(experimentId));

            if (!experimentKey.IsSet)
                throw new ArgumentException("Property is required for class MailCadenceExperimentContext.", nameof(experimentKey));

            if (!exposedAt.IsSet)
                throw new ArgumentException("Property is required for class MailCadenceExperimentContext.", nameof(exposedAt));

            if (!revision.IsSet)
                throw new ArgumentException("Property is required for class MailCadenceExperimentContext.", nameof(revision));

            if (!unitId.IsSet)
                throw new ArgumentException("Property is required for class MailCadenceExperimentContext.", nameof(unitId));

            if (!variantId.IsSet)
                throw new ArgumentException("Property is required for class MailCadenceExperimentContext.", nameof(variantId));

            if (experimentId.IsSet && experimentId.Value == null)
                throw new ArgumentNullException(nameof(experimentId), "Property is not nullable for class MailCadenceExperimentContext.");

            if (experimentKey.IsSet && experimentKey.Value == null)
                throw new ArgumentNullException(nameof(experimentKey), "Property is not nullable for class MailCadenceExperimentContext.");

            if (exposedAt.IsSet && exposedAt.Value == null)
                throw new ArgumentNullException(nameof(exposedAt), "Property is not nullable for class MailCadenceExperimentContext.");

            if (revision.IsSet && revision.Value == null)
                throw new ArgumentNullException(nameof(revision), "Property is not nullable for class MailCadenceExperimentContext.");

            if (unitId.IsSet && unitId.Value == null)
                throw new ArgumentNullException(nameof(unitId), "Property is not nullable for class MailCadenceExperimentContext.");

            if (variantId.IsSet && variantId.Value == null)
                throw new ArgumentNullException(nameof(variantId), "Property is not nullable for class MailCadenceExperimentContext.");

            var reaconModelResult = new MailCadenceExperimentContext(experimentId.Value!, experimentKey.Value!, exposedAt.Value!.Value!, revision.Value!.Value!, unitId.Value!, variantId.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailCadenceExperimentContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailCadenceExperimentContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailCadenceExperimentContext mailCadenceExperimentContext, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailCadenceExperimentContext, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailCadenceExperimentContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailCadenceExperimentContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailCadenceExperimentContext mailCadenceExperimentContext, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailCadenceExperimentContext.ExperimentId == null)
                throw new ArgumentNullException(nameof(mailCadenceExperimentContext.ExperimentId), "Property is required for class MailCadenceExperimentContext.");

            if (mailCadenceExperimentContext.ExperimentKey == null)
                throw new ArgumentNullException(nameof(mailCadenceExperimentContext.ExperimentKey), "Property is required for class MailCadenceExperimentContext.");

            if (mailCadenceExperimentContext.UnitId == null)
                throw new ArgumentNullException(nameof(mailCadenceExperimentContext.UnitId), "Property is required for class MailCadenceExperimentContext.");

            if (mailCadenceExperimentContext.VariantId == null)
                throw new ArgumentNullException(nameof(mailCadenceExperimentContext.VariantId), "Property is required for class MailCadenceExperimentContext.");

            writer.WriteString("experimentId", mailCadenceExperimentContext.ExperimentId);

            writer.WriteString("experimentKey", mailCadenceExperimentContext.ExperimentKey);

            writer.WriteString("exposedAt", mailCadenceExperimentContext.ExposedAt.ToString(ExposedAtFormat));

            writer.WriteNumber("revision", mailCadenceExperimentContext.Revision);

            writer.WriteString("unitId", mailCadenceExperimentContext.UnitId);

            writer.WriteString("variantId", mailCadenceExperimentContext.VariantId);

            foreach (var property in mailCadenceExperimentContext.AdditionalProperties)
            {
                if (property.Key == "experimentId" || property.Key == "experimentKey" || property.Key == "exposedAt" || property.Key == "revision" || property.Key == "unitId" || property.Key == "variantId") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
