// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailGetInboxThreadsResponse200
    /// </summary>
    public partial class MailGetInboxThreadsResponse200 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailGetInboxThreadsResponse200" /> class.
        /// </summary>
        /// <param name="sampleLimited">sampleLimited</param>
        /// <param name="threads">threads</param>
        [JsonConstructor]
        public MailGetInboxThreadsResponse200(bool sampleLimited, List<MailConversationThread> threads)
        {
            SampleLimited = sampleLimited;
            Threads = threads;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SampleLimited
        /// </summary>
        [JsonPropertyName("sampleLimited")]
        public bool SampleLimited { get; set; }

        /// <summary>
        /// Gets or Sets Threads
        /// </summary>
        [JsonPropertyName("threads")]
        public List<MailConversationThread> Threads { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailGetInboxThreadsResponse200 {\n");
            sb.Append("  SampleLimited: ").Append(SampleLimited).Append("\n");
            sb.Append("  Threads: ").Append(Threads).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailGetInboxThreadsResponse200" />
    /// </summary>
    public partial class MailGetInboxThreadsResponse200JsonConverter : JsonConverter<MailGetInboxThreadsResponse200>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailGetInboxThreadsResponse200JsonConverter" /> class.
        /// </summary>
        public MailGetInboxThreadsResponse200JsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailGetInboxThreadsResponse200" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailGetInboxThreadsResponse200 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> sampleLimited = default;
            Option<List<MailConversationThread>?> threads = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sampleLimited":
                            sampleLimited = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "threads":
                            threads = new Option<List<MailConversationThread>?>(JsonSerializer.Deserialize<List<MailConversationThread>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!sampleLimited.IsSet)
                throw new ArgumentException("Property is required for class MailGetInboxThreadsResponse200.", nameof(sampleLimited));

            if (!threads.IsSet)
                throw new ArgumentException("Property is required for class MailGetInboxThreadsResponse200.", nameof(threads));

            if (sampleLimited.IsSet && sampleLimited.Value == null)
                throw new ArgumentNullException(nameof(sampleLimited), "Property is not nullable for class MailGetInboxThreadsResponse200.");

            if (threads.IsSet && threads.Value == null)
                throw new ArgumentNullException(nameof(threads), "Property is not nullable for class MailGetInboxThreadsResponse200.");

            var reaconModelResult = new MailGetInboxThreadsResponse200(sampleLimited.Value!.Value!, threads.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailGetInboxThreadsResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailGetInboxThreadsResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailGetInboxThreadsResponse200 mailGetInboxThreadsResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailGetInboxThreadsResponse200, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailGetInboxThreadsResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailGetInboxThreadsResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailGetInboxThreadsResponse200 mailGetInboxThreadsResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailGetInboxThreadsResponse200.Threads == null)
                throw new ArgumentNullException(nameof(mailGetInboxThreadsResponse200.Threads), "Property is required for class MailGetInboxThreadsResponse200.");

            writer.WriteBoolean("sampleLimited", mailGetInboxThreadsResponse200.SampleLimited);

            writer.WritePropertyName("threads");
            JsonSerializer.Serialize(writer, mailGetInboxThreadsResponse200.Threads, jsonSerializerOptions);

            foreach (var property in mailGetInboxThreadsResponse200.AdditionalProperties)
            {
                if (property.Key == "sampleLimited" || property.Key == "threads") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
