// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPostSuppressionsRequestAnyOf
    /// </summary>
    public partial class MailPostSuppressionsRequestAnyOf : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostSuppressionsRequestAnyOf" /> class.
        /// </summary>
        /// <param name="scope">scope</param>
        /// <param name="value">value</param>
        [JsonConstructor]
        public MailPostSuppressionsRequestAnyOf(ScopeEnum scope, string value)
        {
            Scope = scope;
            Value = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Scope
        /// </summary>
        public enum ScopeEnum
        {
            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 1
        }

        /// <summary>
        /// Returns a <see cref="ScopeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ScopeEnum ScopeEnumFromString(string value)
        {
            if (value.Equals("email"))
                return ScopeEnum.Email;

            throw new NotImplementedException($"Could not convert value to type ScopeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ScopeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ScopeEnum? ScopeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("email"))
                return ScopeEnum.Email;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ScopeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ScopeEnumToJsonValue(ScopeEnum value)
        {
            if (value == ScopeEnum.Email)
                return "email";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Scope
        /// </summary>
        [JsonPropertyName("scope")]
        public ScopeEnum Scope { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPostSuppressionsRequestAnyOf {\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Value (string) maxLength
            if (this.Value != null && this.Value.Length > 320)
            {
                yield return new ValidationResult("Invalid value for Value, length must be less than 320.", new [] { "Value" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPostSuppressionsRequestAnyOf" />
    /// </summary>
    public partial class MailPostSuppressionsRequestAnyOfJsonConverter : JsonConverter<MailPostSuppressionsRequestAnyOf>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostSuppressionsRequestAnyOfJsonConverter" /> class.
        /// </summary>
        public MailPostSuppressionsRequestAnyOfJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPostSuppressionsRequestAnyOf" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPostSuppressionsRequestAnyOf Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<MailPostSuppressionsRequestAnyOf.ScopeEnum?> scope = default;
            Option<string?> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "scope":
                            string? scopeRawValue = utf8JsonReader.GetString();
                            if (scopeRawValue != null)
                            {
                                MailPostSuppressionsRequestAnyOf.ScopeEnum? scopeValue = MailPostSuppressionsRequestAnyOf.ScopeEnumFromStringOrDefault(scopeRawValue);
                                if (scopeValue == null)
                                    throw new JsonException();
                                scope = new Option<MailPostSuppressionsRequestAnyOf.ScopeEnum?>(scopeValue);
                            }
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!scope.IsSet)
                throw new ArgumentException("Property is required for class MailPostSuppressionsRequestAnyOf.", nameof(scope));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class MailPostSuppressionsRequestAnyOf.", nameof(value));

            if (scope.IsSet && scope.Value == null)
                throw new ArgumentNullException(nameof(scope), "Property is not nullable for class MailPostSuppressionsRequestAnyOf.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class MailPostSuppressionsRequestAnyOf.");

            return new MailPostSuppressionsRequestAnyOf(scope.Value!.Value!, value.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MailPostSuppressionsRequestAnyOf" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostSuppressionsRequestAnyOf"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPostSuppressionsRequestAnyOf mailPostSuppressionsRequestAnyOf, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPostSuppressionsRequestAnyOf, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPostSuppressionsRequestAnyOf" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostSuppressionsRequestAnyOf"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPostSuppressionsRequestAnyOf mailPostSuppressionsRequestAnyOf, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPostSuppressionsRequestAnyOf.Value == null)
                throw new ArgumentNullException(nameof(mailPostSuppressionsRequestAnyOf.Value), "Property is required for class MailPostSuppressionsRequestAnyOf.");

            var scopeRawValue = MailPostSuppressionsRequestAnyOf.ScopeEnumToJsonValue(mailPostSuppressionsRequestAnyOf.Scope);
            writer.WriteString("scope", scopeRawValue);
            writer.WriteString("value", mailPostSuppressionsRequestAnyOf.Value);
        }
    }
}
