// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailMailboxHealthRecord
    /// </summary>
    public partial class MailMailboxHealthRecord : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailMailboxHealthRecord" /> class.
        /// </summary>
        /// <param name="accepted7d">accepted7d</param>
        /// <param name="bounced7d">bounced7d</param>
        /// <param name="bounceRate">bounceRate</param>
        /// <param name="complained7d">complained7d</param>
        /// <param name="complaintRate">complaintRate</param>
        /// <param name="currentDailyLimit">currentDailyLimit</param>
        /// <param name="deferred7d">deferred7d</param>
        /// <param name="deferredRate">deferredRate</param>
        /// <param name="delivered7d">delivered7d</param>
        /// <param name="healthScore">healthScore</param>
        /// <param name="mailboxId">mailboxId</param>
        /// <param name="nextRampAt">nextRampAt</param>
        /// <param name="rampEnabled">rampEnabled</param>
        /// <param name="rampIntervalHours">rampIntervalHours</param>
        /// <param name="rampStep">rampStep</param>
        /// <param name="startingDailyLimit">startingDailyLimit</param>
        /// <param name="status">status</param>
        /// <param name="targetDailyLimit">targetDailyLimit</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="lastSignalAt">lastSignalAt</param>
        /// <param name="pauseReason">pauseReason</param>
        [JsonConstructor]
        public MailMailboxHealthRecord(decimal accepted7d, decimal bounced7d, decimal bounceRate, decimal complained7d, decimal complaintRate, decimal currentDailyLimit, decimal deferred7d, decimal deferredRate, decimal delivered7d, decimal healthScore, string mailboxId, DateTimeOffset nextRampAt, bool rampEnabled, decimal rampIntervalHours, decimal rampStep, decimal startingDailyLimit, string status, decimal targetDailyLimit, string tenantId, DateTimeOffset updatedAt, Option<DateTimeOffset?> lastSignalAt = default, Option<string?> pauseReason = default)
        {
            Accepted7d = accepted7d;
            Bounced7d = bounced7d;
            BounceRate = bounceRate;
            Complained7d = complained7d;
            ComplaintRate = complaintRate;
            CurrentDailyLimit = currentDailyLimit;
            Deferred7d = deferred7d;
            DeferredRate = deferredRate;
            Delivered7d = delivered7d;
            HealthScore = healthScore;
            MailboxId = mailboxId;
            NextRampAt = nextRampAt;
            RampEnabled = rampEnabled;
            RampIntervalHours = rampIntervalHours;
            RampStep = rampStep;
            StartingDailyLimit = startingDailyLimit;
            Status = status;
            TargetDailyLimit = targetDailyLimit;
            TenantId = tenantId;
            UpdatedAt = updatedAt;
            LastSignalAtOption = lastSignalAt;
            PauseReasonOption = pauseReason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Accepted7d
        /// </summary>
        [JsonPropertyName("accepted7d")]
        public decimal Accepted7d { get; set; }

        /// <summary>
        /// Gets or Sets Bounced7d
        /// </summary>
        [JsonPropertyName("bounced7d")]
        public decimal Bounced7d { get; set; }

        /// <summary>
        /// Gets or Sets BounceRate
        /// </summary>
        [JsonPropertyName("bounceRate")]
        public decimal BounceRate { get; set; }

        /// <summary>
        /// Gets or Sets Complained7d
        /// </summary>
        [JsonPropertyName("complained7d")]
        public decimal Complained7d { get; set; }

        /// <summary>
        /// Gets or Sets ComplaintRate
        /// </summary>
        [JsonPropertyName("complaintRate")]
        public decimal ComplaintRate { get; set; }

        /// <summary>
        /// Gets or Sets CurrentDailyLimit
        /// </summary>
        [JsonPropertyName("currentDailyLimit")]
        public decimal CurrentDailyLimit { get; set; }

        /// <summary>
        /// Gets or Sets Deferred7d
        /// </summary>
        [JsonPropertyName("deferred7d")]
        public decimal Deferred7d { get; set; }

        /// <summary>
        /// Gets or Sets DeferredRate
        /// </summary>
        [JsonPropertyName("deferredRate")]
        public decimal DeferredRate { get; set; }

        /// <summary>
        /// Gets or Sets Delivered7d
        /// </summary>
        [JsonPropertyName("delivered7d")]
        public decimal Delivered7d { get; set; }

        /// <summary>
        /// Gets or Sets HealthScore
        /// </summary>
        [JsonPropertyName("healthScore")]
        public decimal HealthScore { get; set; }

        /// <summary>
        /// Gets or Sets MailboxId
        /// </summary>
        [JsonPropertyName("mailboxId")]
        public string MailboxId { get; set; }

        /// <summary>
        /// Gets or Sets NextRampAt
        /// </summary>
        [JsonPropertyName("nextRampAt")]
        public DateTimeOffset NextRampAt { get; set; }

        /// <summary>
        /// Gets or Sets RampEnabled
        /// </summary>
        [JsonPropertyName("rampEnabled")]
        public bool RampEnabled { get; set; }

        /// <summary>
        /// Gets or Sets RampIntervalHours
        /// </summary>
        [JsonPropertyName("rampIntervalHours")]
        public decimal RampIntervalHours { get; set; }

        /// <summary>
        /// Gets or Sets RampStep
        /// </summary>
        [JsonPropertyName("rampStep")]
        public decimal RampStep { get; set; }

        /// <summary>
        /// Gets or Sets StartingDailyLimit
        /// </summary>
        [JsonPropertyName("startingDailyLimit")]
        public decimal StartingDailyLimit { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets TargetDailyLimit
        /// </summary>
        [JsonPropertyName("targetDailyLimit")]
        public decimal TargetDailyLimit { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of LastSignalAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> LastSignalAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastSignalAt
        /// </summary>
        [JsonPropertyName("lastSignalAt")]
        public DateTimeOffset? LastSignalAt { get { return this.LastSignalAtOption.Value; } set { this.LastSignalAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of PauseReason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PauseReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets PauseReason
        /// </summary>
        [JsonPropertyName("pauseReason")]
        public string? PauseReason { get { return this.PauseReasonOption.Value; } set { this.PauseReasonOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailMailboxHealthRecord {\n");
            sb.Append("  Accepted7d: ").Append(Accepted7d).Append("\n");
            sb.Append("  Bounced7d: ").Append(Bounced7d).Append("\n");
            sb.Append("  BounceRate: ").Append(BounceRate).Append("\n");
            sb.Append("  Complained7d: ").Append(Complained7d).Append("\n");
            sb.Append("  ComplaintRate: ").Append(ComplaintRate).Append("\n");
            sb.Append("  CurrentDailyLimit: ").Append(CurrentDailyLimit).Append("\n");
            sb.Append("  Deferred7d: ").Append(Deferred7d).Append("\n");
            sb.Append("  DeferredRate: ").Append(DeferredRate).Append("\n");
            sb.Append("  Delivered7d: ").Append(Delivered7d).Append("\n");
            sb.Append("  HealthScore: ").Append(HealthScore).Append("\n");
            sb.Append("  MailboxId: ").Append(MailboxId).Append("\n");
            sb.Append("  NextRampAt: ").Append(NextRampAt).Append("\n");
            sb.Append("  RampEnabled: ").Append(RampEnabled).Append("\n");
            sb.Append("  RampIntervalHours: ").Append(RampIntervalHours).Append("\n");
            sb.Append("  RampStep: ").Append(RampStep).Append("\n");
            sb.Append("  StartingDailyLimit: ").Append(StartingDailyLimit).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TargetDailyLimit: ").Append(TargetDailyLimit).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  LastSignalAt: ").Append(LastSignalAt).Append("\n");
            sb.Append("  PauseReason: ").Append(PauseReason).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailMailboxHealthRecord" />
    /// </summary>
    public partial class MailMailboxHealthRecordJsonConverter : JsonConverter<MailMailboxHealthRecord>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailMailboxHealthRecordJsonConverter" /> class.
        /// </summary>
        public MailMailboxHealthRecordJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize NextRampAt
        /// </summary>
        public string NextRampAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastSignalAt
        /// </summary>
        public string LastSignalAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MailMailboxHealthRecord" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailMailboxHealthRecord Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> accepted7d = default;
            Option<decimal?> bounced7d = default;
            Option<decimal?> bounceRate = default;
            Option<decimal?> complained7d = default;
            Option<decimal?> complaintRate = default;
            Option<decimal?> currentDailyLimit = default;
            Option<decimal?> deferred7d = default;
            Option<decimal?> deferredRate = default;
            Option<decimal?> delivered7d = default;
            Option<decimal?> healthScore = default;
            Option<string?> mailboxId = default;
            Option<DateTimeOffset?> nextRampAt = default;
            Option<bool?> rampEnabled = default;
            Option<decimal?> rampIntervalHours = default;
            Option<decimal?> rampStep = default;
            Option<decimal?> startingDailyLimit = default;
            Option<string?> status = default;
            Option<decimal?> targetDailyLimit = default;
            Option<string?> tenantId = default;
            Option<DateTimeOffset?> updatedAt = default;
            Option<DateTimeOffset?> lastSignalAt = default;
            Option<string?> pauseReason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "accepted7d":
                            accepted7d = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "bounced7d":
                            bounced7d = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "bounceRate":
                            bounceRate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "complained7d":
                            complained7d = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "complaintRate":
                            complaintRate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "currentDailyLimit":
                            currentDailyLimit = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "deferred7d":
                            deferred7d = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "deferredRate":
                            deferredRate = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "delivered7d":
                            delivered7d = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "healthScore":
                            healthScore = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "mailboxId":
                            mailboxId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nextRampAt":
                            nextRampAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "rampEnabled":
                            rampEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "rampIntervalHours":
                            rampIntervalHours = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "rampStep":
                            rampStep = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "startingDailyLimit":
                            startingDailyLimit = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "targetDailyLimit":
                            targetDailyLimit = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "lastSignalAt":
                            lastSignalAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pauseReason":
                            pauseReason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!accepted7d.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(accepted7d));

            if (!bounced7d.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(bounced7d));

            if (!bounceRate.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(bounceRate));

            if (!complained7d.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(complained7d));

            if (!complaintRate.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(complaintRate));

            if (!currentDailyLimit.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(currentDailyLimit));

            if (!deferred7d.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(deferred7d));

            if (!deferredRate.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(deferredRate));

            if (!delivered7d.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(delivered7d));

            if (!healthScore.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(healthScore));

            if (!mailboxId.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(mailboxId));

            if (!nextRampAt.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(nextRampAt));

            if (!rampEnabled.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(rampEnabled));

            if (!rampIntervalHours.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(rampIntervalHours));

            if (!rampStep.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(rampStep));

            if (!startingDailyLimit.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(startingDailyLimit));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(status));

            if (!targetDailyLimit.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(targetDailyLimit));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(tenantId));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class MailMailboxHealthRecord.", nameof(updatedAt));

            if (accepted7d.IsSet && accepted7d.Value == null)
                throw new ArgumentNullException(nameof(accepted7d), "Property is not nullable for class MailMailboxHealthRecord.");

            if (bounced7d.IsSet && bounced7d.Value == null)
                throw new ArgumentNullException(nameof(bounced7d), "Property is not nullable for class MailMailboxHealthRecord.");

            if (bounceRate.IsSet && bounceRate.Value == null)
                throw new ArgumentNullException(nameof(bounceRate), "Property is not nullable for class MailMailboxHealthRecord.");

            if (complained7d.IsSet && complained7d.Value == null)
                throw new ArgumentNullException(nameof(complained7d), "Property is not nullable for class MailMailboxHealthRecord.");

            if (complaintRate.IsSet && complaintRate.Value == null)
                throw new ArgumentNullException(nameof(complaintRate), "Property is not nullable for class MailMailboxHealthRecord.");

            if (currentDailyLimit.IsSet && currentDailyLimit.Value == null)
                throw new ArgumentNullException(nameof(currentDailyLimit), "Property is not nullable for class MailMailboxHealthRecord.");

            if (deferred7d.IsSet && deferred7d.Value == null)
                throw new ArgumentNullException(nameof(deferred7d), "Property is not nullable for class MailMailboxHealthRecord.");

            if (deferredRate.IsSet && deferredRate.Value == null)
                throw new ArgumentNullException(nameof(deferredRate), "Property is not nullable for class MailMailboxHealthRecord.");

            if (delivered7d.IsSet && delivered7d.Value == null)
                throw new ArgumentNullException(nameof(delivered7d), "Property is not nullable for class MailMailboxHealthRecord.");

            if (healthScore.IsSet && healthScore.Value == null)
                throw new ArgumentNullException(nameof(healthScore), "Property is not nullable for class MailMailboxHealthRecord.");

            if (mailboxId.IsSet && mailboxId.Value == null)
                throw new ArgumentNullException(nameof(mailboxId), "Property is not nullable for class MailMailboxHealthRecord.");

            if (nextRampAt.IsSet && nextRampAt.Value == null)
                throw new ArgumentNullException(nameof(nextRampAt), "Property is not nullable for class MailMailboxHealthRecord.");

            if (rampEnabled.IsSet && rampEnabled.Value == null)
                throw new ArgumentNullException(nameof(rampEnabled), "Property is not nullable for class MailMailboxHealthRecord.");

            if (rampIntervalHours.IsSet && rampIntervalHours.Value == null)
                throw new ArgumentNullException(nameof(rampIntervalHours), "Property is not nullable for class MailMailboxHealthRecord.");

            if (rampStep.IsSet && rampStep.Value == null)
                throw new ArgumentNullException(nameof(rampStep), "Property is not nullable for class MailMailboxHealthRecord.");

            if (startingDailyLimit.IsSet && startingDailyLimit.Value == null)
                throw new ArgumentNullException(nameof(startingDailyLimit), "Property is not nullable for class MailMailboxHealthRecord.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class MailMailboxHealthRecord.");

            if (targetDailyLimit.IsSet && targetDailyLimit.Value == null)
                throw new ArgumentNullException(nameof(targetDailyLimit), "Property is not nullable for class MailMailboxHealthRecord.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class MailMailboxHealthRecord.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class MailMailboxHealthRecord.");

            if (lastSignalAt.IsSet && lastSignalAt.Value == null)
                throw new ArgumentNullException(nameof(lastSignalAt), "Property is not nullable for class MailMailboxHealthRecord.");

            if (pauseReason.IsSet && pauseReason.Value == null)
                throw new ArgumentNullException(nameof(pauseReason), "Property is not nullable for class MailMailboxHealthRecord.");

            var reaconModelResult = new MailMailboxHealthRecord(accepted7d.Value!.Value!, bounced7d.Value!.Value!, bounceRate.Value!.Value!, complained7d.Value!.Value!, complaintRate.Value!.Value!, currentDailyLimit.Value!.Value!, deferred7d.Value!.Value!, deferredRate.Value!.Value!, delivered7d.Value!.Value!, healthScore.Value!.Value!, mailboxId.Value!, nextRampAt.Value!.Value!, rampEnabled.Value!.Value!, rampIntervalHours.Value!.Value!, rampStep.Value!.Value!, startingDailyLimit.Value!.Value!, status.Value!, targetDailyLimit.Value!.Value!, tenantId.Value!, updatedAt.Value!.Value!, lastSignalAt, pauseReason);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailMailboxHealthRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailMailboxHealthRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailMailboxHealthRecord mailMailboxHealthRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailMailboxHealthRecord, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailMailboxHealthRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailMailboxHealthRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailMailboxHealthRecord mailMailboxHealthRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailMailboxHealthRecord.MailboxId == null)
                throw new ArgumentNullException(nameof(mailMailboxHealthRecord.MailboxId), "Property is required for class MailMailboxHealthRecord.");

            if (mailMailboxHealthRecord.Status == null)
                throw new ArgumentNullException(nameof(mailMailboxHealthRecord.Status), "Property is required for class MailMailboxHealthRecord.");

            if (mailMailboxHealthRecord.TenantId == null)
                throw new ArgumentNullException(nameof(mailMailboxHealthRecord.TenantId), "Property is required for class MailMailboxHealthRecord.");

            if (mailMailboxHealthRecord.PauseReasonOption.IsSet && mailMailboxHealthRecord.PauseReason == null)
                throw new ArgumentNullException(nameof(mailMailboxHealthRecord.PauseReason), "Property is required for class MailMailboxHealthRecord.");

            writer.WriteNumber("accepted7d", mailMailboxHealthRecord.Accepted7d);

            writer.WriteNumber("bounced7d", mailMailboxHealthRecord.Bounced7d);

            writer.WriteNumber("bounceRate", mailMailboxHealthRecord.BounceRate);

            writer.WriteNumber("complained7d", mailMailboxHealthRecord.Complained7d);

            writer.WriteNumber("complaintRate", mailMailboxHealthRecord.ComplaintRate);

            writer.WriteNumber("currentDailyLimit", mailMailboxHealthRecord.CurrentDailyLimit);

            writer.WriteNumber("deferred7d", mailMailboxHealthRecord.Deferred7d);

            writer.WriteNumber("deferredRate", mailMailboxHealthRecord.DeferredRate);

            writer.WriteNumber("delivered7d", mailMailboxHealthRecord.Delivered7d);

            writer.WriteNumber("healthScore", mailMailboxHealthRecord.HealthScore);

            writer.WriteString("mailboxId", mailMailboxHealthRecord.MailboxId);

            writer.WriteString("nextRampAt", mailMailboxHealthRecord.NextRampAt.ToString(NextRampAtFormat));

            writer.WriteBoolean("rampEnabled", mailMailboxHealthRecord.RampEnabled);

            writer.WriteNumber("rampIntervalHours", mailMailboxHealthRecord.RampIntervalHours);

            writer.WriteNumber("rampStep", mailMailboxHealthRecord.RampStep);

            writer.WriteNumber("startingDailyLimit", mailMailboxHealthRecord.StartingDailyLimit);

            writer.WriteString("status", mailMailboxHealthRecord.Status);

            writer.WriteNumber("targetDailyLimit", mailMailboxHealthRecord.TargetDailyLimit);

            writer.WriteString("tenantId", mailMailboxHealthRecord.TenantId);

            writer.WriteString("updatedAt", mailMailboxHealthRecord.UpdatedAt.ToString(UpdatedAtFormat));

            if (mailMailboxHealthRecord.LastSignalAtOption.IsSet)
                writer.WriteString("lastSignalAt", mailMailboxHealthRecord.LastSignalAtOption.Value!.Value.ToString(LastSignalAtFormat));

            if (mailMailboxHealthRecord.PauseReasonOption.IsSet)
                writer.WriteString("pauseReason", mailMailboxHealthRecord.PauseReason);

            foreach (var property in mailMailboxHealthRecord.AdditionalProperties)
            {
                if (property.Key == "accepted7d" || property.Key == "bounced7d" || property.Key == "bounceRate" || property.Key == "complained7d" || property.Key == "complaintRate" || property.Key == "currentDailyLimit" || property.Key == "deferred7d" || property.Key == "deferredRate" || property.Key == "delivered7d" || property.Key == "healthScore" || property.Key == "mailboxId" || property.Key == "nextRampAt" || property.Key == "rampEnabled" || property.Key == "rampIntervalHours" || property.Key == "rampStep" || property.Key == "startingDailyLimit" || property.Key == "status" || property.Key == "targetDailyLimit" || property.Key == "tenantId" || property.Key == "updatedAt" || property.Key == "lastSignalAt" || property.Key == "pauseReason") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
