// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200
    /// </summary>
    public partial class MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200" /> class.
        /// </summary>
        /// <param name="member">member</param>
        [JsonConstructor]
        public MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200(MailMailboxPoolMember member)
        {
            Member = member;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Member
        /// </summary>
        [JsonPropertyName("member")]
        public MailMailboxPoolMember Member { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 {\n");
            sb.Append("  Member: ").Append(Member).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200" />
    /// </summary>
    public partial class MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200JsonConverter : JsonConverter<MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200JsonConverter" /> class.
        /// </summary>
        public MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200JsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<MailMailboxPoolMember?> member = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "member":
                            member = new Option<MailMailboxPoolMember?>(JsonSerializer.Deserialize<MailMailboxPoolMember>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!member.IsSet)
                throw new ArgumentException("Property is required for class MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.", nameof(member));

            if (member.IsSet && member.Value == null)
                throw new ArgumentNullException(nameof(member), "Property is not nullable for class MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.");

            var reaconModelResult = new MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200(member.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200 mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.Member == null)
                throw new ArgumentNullException(nameof(mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.Member), "Property is required for class MailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.");

            writer.WritePropertyName("member");
            JsonSerializer.Serialize(writer, mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.Member, jsonSerializerOptions);

            foreach (var property in mailPutDeliverabilityPoolsByPoolIdMembersByMailboxIdResponse200.AdditionalProperties)
            {
                if (property.Key == "member") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
