// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200
    /// </summary>
    public partial class MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200" /> class.
        /// </summary>
        /// <param name="health">health</param>
        [JsonConstructor]
        public MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200(MailMailboxHealthRecord health)
        {
            Health = health;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Health
        /// </summary>
        [JsonPropertyName("health")]
        public MailMailboxHealthRecord Health { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 {\n");
            sb.Append("  Health: ").Append(Health).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200" />
    /// </summary>
    public partial class MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200JsonConverter : JsonConverter<MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200JsonConverter" /> class.
        /// </summary>
        public MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200JsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<MailMailboxHealthRecord?> health = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "health":
                            health = new Option<MailMailboxHealthRecord?>(JsonSerializer.Deserialize<MailMailboxHealthRecord>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!health.IsSet)
                throw new ArgumentException("Property is required for class MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.", nameof(health));

            if (health.IsSet && health.Value == null)
                throw new ArgumentNullException(nameof(health), "Property is not nullable for class MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.");

            var reaconModelResult = new MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200(health.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200 mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.Health == null)
                throw new ArgumentNullException(nameof(mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.Health), "Property is required for class MailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.");

            writer.WritePropertyName("health");
            JsonSerializer.Serialize(writer, mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.Health, jsonSerializerOptions);

            foreach (var property in mailPostDeliverabilityMailboxesByMailboxIdReconcileResponse200.AdditionalProperties)
            {
                if (property.Key == "health") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
