// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailReplyAutomationRule
    /// </summary>
    public partial class MailReplyAutomationRule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailReplyAutomationRule" /> class.
        /// </summary>
        /// <param name="actions">actions</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="enabled">enabled</param>
        /// <param name="id">id</param>
        /// <param name="labels">labels</param>
        /// <param name="name">name</param>
        /// <param name="priority">priority</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="updatedAt">updatedAt</param>
        [JsonConstructor]
        public MailReplyAutomationRule(MailReplyAutomationRuleActions actions, DateTimeOffset createdAt, bool enabled, string id, List<string> labels, string name, decimal priority, string tenantId, DateTimeOffset updatedAt)
        {
            Actions = actions;
            CreatedAt = createdAt;
            Enabled = enabled;
            Id = id;
            Labels = labels;
            Name = name;
            Priority = priority;
            TenantId = tenantId;
            UpdatedAt = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Actions
        /// </summary>
        [JsonPropertyName("actions")]
        public MailReplyAutomationRuleActions Actions { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [JsonPropertyName("labels")]
        public List<string> Labels { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [JsonPropertyName("priority")]
        public decimal Priority { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailReplyAutomationRule {\n");
            sb.Append("  Actions: ").Append(Actions).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailReplyAutomationRule" />
    /// </summary>
    public partial class MailReplyAutomationRuleJsonConverter : JsonConverter<MailReplyAutomationRule>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailReplyAutomationRuleJsonConverter" /> class.
        /// </summary>
        public MailReplyAutomationRuleJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MailReplyAutomationRule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailReplyAutomationRule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<MailReplyAutomationRuleActions?> actions = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<bool?> enabled = default;
            Option<string?> id = default;
            Option<List<string>?> labels = default;
            Option<string?> name = default;
            Option<decimal?> priority = default;
            Option<string?> tenantId = default;
            Option<DateTimeOffset?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "actions":
                            actions = new Option<MailReplyAutomationRuleActions?>(JsonSerializer.Deserialize<MailReplyAutomationRuleActions>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "labels":
                            labels = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "priority":
                            priority = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "tenantId":
                            tenantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!actions.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(actions));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(createdAt));

            if (!enabled.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(enabled));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(id));

            if (!labels.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(labels));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(name));

            if (!priority.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(priority));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(tenantId));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class MailReplyAutomationRule.", nameof(updatedAt));

            if (actions.IsSet && actions.Value == null)
                throw new ArgumentNullException(nameof(actions), "Property is not nullable for class MailReplyAutomationRule.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class MailReplyAutomationRule.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class MailReplyAutomationRule.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class MailReplyAutomationRule.");

            if (labels.IsSet && labels.Value == null)
                throw new ArgumentNullException(nameof(labels), "Property is not nullable for class MailReplyAutomationRule.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class MailReplyAutomationRule.");

            if (priority.IsSet && priority.Value == null)
                throw new ArgumentNullException(nameof(priority), "Property is not nullable for class MailReplyAutomationRule.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class MailReplyAutomationRule.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class MailReplyAutomationRule.");

            var reaconModelResult = new MailReplyAutomationRule(actions.Value!, createdAt.Value!.Value!, enabled.Value!.Value!, id.Value!, labels.Value!, name.Value!, priority.Value!.Value!, tenantId.Value!, updatedAt.Value!.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailReplyAutomationRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailReplyAutomationRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailReplyAutomationRule mailReplyAutomationRule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailReplyAutomationRule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailReplyAutomationRule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailReplyAutomationRule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailReplyAutomationRule mailReplyAutomationRule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailReplyAutomationRule.Actions == null)
                throw new ArgumentNullException(nameof(mailReplyAutomationRule.Actions), "Property is required for class MailReplyAutomationRule.");

            if (mailReplyAutomationRule.Id == null)
                throw new ArgumentNullException(nameof(mailReplyAutomationRule.Id), "Property is required for class MailReplyAutomationRule.");

            if (mailReplyAutomationRule.Labels == null)
                throw new ArgumentNullException(nameof(mailReplyAutomationRule.Labels), "Property is required for class MailReplyAutomationRule.");

            if (mailReplyAutomationRule.Name == null)
                throw new ArgumentNullException(nameof(mailReplyAutomationRule.Name), "Property is required for class MailReplyAutomationRule.");

            if (mailReplyAutomationRule.TenantId == null)
                throw new ArgumentNullException(nameof(mailReplyAutomationRule.TenantId), "Property is required for class MailReplyAutomationRule.");

            writer.WritePropertyName("actions");
            JsonSerializer.Serialize(writer, mailReplyAutomationRule.Actions, jsonSerializerOptions);
            writer.WriteString("createdAt", mailReplyAutomationRule.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteBoolean("enabled", mailReplyAutomationRule.Enabled);

            writer.WriteString("id", mailReplyAutomationRule.Id);

            writer.WritePropertyName("labels");
            JsonSerializer.Serialize(writer, mailReplyAutomationRule.Labels, jsonSerializerOptions);
            writer.WriteString("name", mailReplyAutomationRule.Name);

            writer.WriteNumber("priority", mailReplyAutomationRule.Priority);

            writer.WriteString("tenantId", mailReplyAutomationRule.TenantId);

            writer.WriteString("updatedAt", mailReplyAutomationRule.UpdatedAt.ToString(UpdatedAtFormat));

            foreach (var property in mailReplyAutomationRule.AdditionalProperties)
            {
                if (property.Key == "actions" || property.Key == "createdAt" || property.Key == "enabled" || property.Key == "id" || property.Key == "labels" || property.Key == "name" || property.Key == "priority" || property.Key == "tenantId" || property.Key == "updatedAt") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
