// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPostTemplatesRequest
    /// </summary>
    public partial class MailPostTemplatesRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostTemplatesRequest" /> class.
        /// </summary>
        /// <param name="body">body</param>
        /// <param name="channel">channel</param>
        /// <param name="name">name</param>
        /// <param name="status">status</param>
        /// <param name="id">id</param>
        /// <param name="subject">subject</param>
        /// <param name="whatsappApproval">whatsappApproval</param>
        [JsonConstructor]
        public MailPostTemplatesRequest(string body, ChannelEnum channel, string name, StatusEnum status, Option<string?> id = default, Option<string?> subject = default, Option<MailPostTemplatesRequestWhatsappApproval?> whatsappApproval = default)
        {
            Body = body;
            Channel = channel;
            Name = name;
            Status = status;
            IdOption = id;
            SubjectOption = subject;
            WhatsappApprovalOption = whatsappApproval;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Channel
        /// </summary>
        public enum ChannelEnum
        {
            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 1,

            /// <summary>
            /// Enum Sms for value: sms
            /// </summary>
            Sms = 2,

            /// <summary>
            /// Enum Whatsapp for value: whatsapp
            /// </summary>
            Whatsapp = 3
        }

        /// <summary>
        /// Returns a <see cref="ChannelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ChannelEnum ChannelEnumFromString(string value)
        {
            if (value.Equals("email"))
                return ChannelEnum.Email;

            if (value.Equals("sms"))
                return ChannelEnum.Sms;

            if (value.Equals("whatsapp"))
                return ChannelEnum.Whatsapp;

            throw new NotImplementedException($"Could not convert value to type ChannelEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ChannelEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ChannelEnum? ChannelEnumFromStringOrDefault(string value)
        {
            if (value.Equals("email"))
                return ChannelEnum.Email;

            if (value.Equals("sms"))
                return ChannelEnum.Sms;

            if (value.Equals("whatsapp"))
                return ChannelEnum.Whatsapp;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ChannelEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ChannelEnumToJsonValue(ChannelEnum value)
        {
            if (value == ChannelEnum.Email)
                return "email";

            if (value == ChannelEnum.Sms)
                return "sms";

            if (value == ChannelEnum.Whatsapp)
                return "whatsapp";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>
        [JsonPropertyName("channel")]
        public ChannelEnum Channel { get; set; }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            Draft = 1,

            /// <summary>
            /// Enum Published for value: published
            /// </summary>
            Published = 2,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            Archived = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("draft"))
                return StatusEnum.Draft;

            if (value.Equals("published"))
                return StatusEnum.Published;

            if (value.Equals("archived"))
                return StatusEnum.Archived;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("draft"))
                return StatusEnum.Draft;

            if (value.Equals("published"))
                return StatusEnum.Published;

            if (value.Equals("archived"))
                return StatusEnum.Archived;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Draft)
                return "draft";

            if (value == StatusEnum.Published)
                return "published";

            if (value == StatusEnum.Archived)
                return "archived";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of WhatsappApproval
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailPostTemplatesRequestWhatsappApproval?> WhatsappApprovalOption { get; private set; }

        /// <summary>
        /// Gets or Sets WhatsappApproval
        /// </summary>
        [JsonPropertyName("whatsappApproval")]
        public MailPostTemplatesRequestWhatsappApproval? WhatsappApproval { get { return this.WhatsappApprovalOption.Value; } set { this.WhatsappApprovalOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPostTemplatesRequest {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  WhatsappApproval: ").Append(WhatsappApproval).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Body (string) maxLength
            if (this.Body != null && this.Body.Length > 200000)
            {
                yield return new ValidationResult("Invalid value for Body, length must be less than 200000.", new [] { "Body" });
            }

            // Body (string) minLength
            if (this.Body != null && this.Body.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Body, length must be greater than 1.", new [] { "Body" });
            }

            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Id (string) maxLength
            if (this.Id != null && this.Id.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Id, length must be less than 200.", new [] { "Id" });
            }

            // Id (string) minLength
            if (this.Id != null && this.Id.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Id, length must be greater than 1.", new [] { "Id" });
            }

            // Subject (string) maxLength
            if (this.Subject != null && this.Subject.Length > 998)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be less than 998.", new [] { "Subject" });
            }

            // Subject (string) minLength
            if (this.Subject != null && this.Subject.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be greater than 1.", new [] { "Subject" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPostTemplatesRequest" />
    /// </summary>
    public partial class MailPostTemplatesRequestJsonConverter : JsonConverter<MailPostTemplatesRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostTemplatesRequestJsonConverter" /> class.
        /// </summary>
        public MailPostTemplatesRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPostTemplatesRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPostTemplatesRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> body = default;
            Option<MailPostTemplatesRequest.ChannelEnum?> channel = default;
            Option<string?> name = default;
            Option<MailPostTemplatesRequest.StatusEnum?> status = default;
            Option<string?> id = default;
            Option<string?> subject = default;
            Option<MailPostTemplatesRequestWhatsappApproval?> whatsappApproval = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "channel":
                            string? channelRawValue = utf8JsonReader.GetString();
                            if (channelRawValue != null)
                            {
                                MailPostTemplatesRequest.ChannelEnum? channelValue = MailPostTemplatesRequest.ChannelEnumFromStringOrDefault(channelRawValue);
                                if (channelValue == null)
                                    throw new JsonException();
                                channel = new Option<MailPostTemplatesRequest.ChannelEnum?>(channelValue);
                            }
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                MailPostTemplatesRequest.StatusEnum? statusValue = MailPostTemplatesRequest.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<MailPostTemplatesRequest.StatusEnum?>(statusValue);
                            }
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "whatsappApproval":
                            whatsappApproval = new Option<MailPostTemplatesRequestWhatsappApproval?>(JsonSerializer.Deserialize<MailPostTemplatesRequestWhatsappApproval>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!body.IsSet)
                throw new ArgumentException("Property is required for class MailPostTemplatesRequest.", nameof(body));

            if (!channel.IsSet)
                throw new ArgumentException("Property is required for class MailPostTemplatesRequest.", nameof(channel));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class MailPostTemplatesRequest.", nameof(name));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class MailPostTemplatesRequest.", nameof(status));

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class MailPostTemplatesRequest.");

            if (channel.IsSet && channel.Value == null)
                throw new ArgumentNullException(nameof(channel), "Property is not nullable for class MailPostTemplatesRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class MailPostTemplatesRequest.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class MailPostTemplatesRequest.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class MailPostTemplatesRequest.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class MailPostTemplatesRequest.");

            if (whatsappApproval.IsSet && whatsappApproval.Value == null)
                throw new ArgumentNullException(nameof(whatsappApproval), "Property is not nullable for class MailPostTemplatesRequest.");

            return new MailPostTemplatesRequest(body.Value!, channel.Value!.Value!, name.Value!, status.Value!.Value!, id, subject, whatsappApproval);
        }

        /// <summary>
        /// Serializes a <see cref="MailPostTemplatesRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostTemplatesRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPostTemplatesRequest mailPostTemplatesRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPostTemplatesRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPostTemplatesRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostTemplatesRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPostTemplatesRequest mailPostTemplatesRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPostTemplatesRequest.Body == null)
                throw new ArgumentNullException(nameof(mailPostTemplatesRequest.Body), "Property is required for class MailPostTemplatesRequest.");

            if (mailPostTemplatesRequest.Name == null)
                throw new ArgumentNullException(nameof(mailPostTemplatesRequest.Name), "Property is required for class MailPostTemplatesRequest.");

            if (mailPostTemplatesRequest.IdOption.IsSet && mailPostTemplatesRequest.Id == null)
                throw new ArgumentNullException(nameof(mailPostTemplatesRequest.Id), "Property is required for class MailPostTemplatesRequest.");

            if (mailPostTemplatesRequest.SubjectOption.IsSet && mailPostTemplatesRequest.Subject == null)
                throw new ArgumentNullException(nameof(mailPostTemplatesRequest.Subject), "Property is required for class MailPostTemplatesRequest.");

            if (mailPostTemplatesRequest.WhatsappApprovalOption.IsSet && mailPostTemplatesRequest.WhatsappApproval == null)
                throw new ArgumentNullException(nameof(mailPostTemplatesRequest.WhatsappApproval), "Property is required for class MailPostTemplatesRequest.");

            writer.WriteString("body", mailPostTemplatesRequest.Body);

            var channelRawValue = MailPostTemplatesRequest.ChannelEnumToJsonValue(mailPostTemplatesRequest.Channel);
            writer.WriteString("channel", channelRawValue);
            writer.WriteString("name", mailPostTemplatesRequest.Name);

            var statusRawValue = MailPostTemplatesRequest.StatusEnumToJsonValue(mailPostTemplatesRequest.Status);
            writer.WriteString("status", statusRawValue);
            if (mailPostTemplatesRequest.IdOption.IsSet)
                writer.WriteString("id", mailPostTemplatesRequest.Id);

            if (mailPostTemplatesRequest.SubjectOption.IsSet)
                writer.WriteString("subject", mailPostTemplatesRequest.Subject);

            if (mailPostTemplatesRequest.WhatsappApprovalOption.IsSet)
            {
                writer.WritePropertyName("whatsappApproval");
                JsonSerializer.Serialize(writer, mailPostTemplatesRequest.WhatsappApproval, jsonSerializerOptions);
            }
        }
    }
}
