// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPostAnalyticsExportResponse200NextCursor
    /// </summary>
    public partial class MailPostAnalyticsExportResponse200NextCursor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostAnalyticsExportResponse200NextCursor" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt</param>
        /// <param name="id">id</param>
        [JsonConstructor]
        public MailPostAnalyticsExportResponse200NextCursor(string createdAt, string id)
        {
            CreatedAt = createdAt;
            Id = id;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPostAnalyticsExportResponse200NextCursor {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPostAnalyticsExportResponse200NextCursor" />
    /// </summary>
    public partial class MailPostAnalyticsExportResponse200NextCursorJsonConverter : JsonConverter<MailPostAnalyticsExportResponse200NextCursor>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostAnalyticsExportResponse200NextCursorJsonConverter" /> class.
        /// </summary>
        public MailPostAnalyticsExportResponse200NextCursorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPostAnalyticsExportResponse200NextCursor" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPostAnalyticsExportResponse200NextCursor Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> createdAt = default;
            Option<string?> id = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "createdAt":
                            createdAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class MailPostAnalyticsExportResponse200NextCursor.", nameof(createdAt));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class MailPostAnalyticsExportResponse200NextCursor.", nameof(id));

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class MailPostAnalyticsExportResponse200NextCursor.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class MailPostAnalyticsExportResponse200NextCursor.");

            var reaconModelResult = new MailPostAnalyticsExportResponse200NextCursor(createdAt.Value!, id.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailPostAnalyticsExportResponse200NextCursor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostAnalyticsExportResponse200NextCursor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPostAnalyticsExportResponse200NextCursor mailPostAnalyticsExportResponse200NextCursor, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPostAnalyticsExportResponse200NextCursor, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPostAnalyticsExportResponse200NextCursor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostAnalyticsExportResponse200NextCursor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPostAnalyticsExportResponse200NextCursor mailPostAnalyticsExportResponse200NextCursor, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPostAnalyticsExportResponse200NextCursor.CreatedAt == null)
                throw new ArgumentNullException(nameof(mailPostAnalyticsExportResponse200NextCursor.CreatedAt), "Property is required for class MailPostAnalyticsExportResponse200NextCursor.");

            if (mailPostAnalyticsExportResponse200NextCursor.Id == null)
                throw new ArgumentNullException(nameof(mailPostAnalyticsExportResponse200NextCursor.Id), "Property is required for class MailPostAnalyticsExportResponse200NextCursor.");

            writer.WriteString("createdAt", mailPostAnalyticsExportResponse200NextCursor.CreatedAt);

            writer.WriteString("id", mailPostAnalyticsExportResponse200NextCursor.Id);

            foreach (var property in mailPostAnalyticsExportResponse200NextCursor.AdditionalProperties)
            {
                if (property.Key == "createdAt" || property.Key == "id") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
