// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailConversationEntryLastError
    /// </summary>
    public partial class MailConversationEntryLastError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailConversationEntryLastError" /> class.
        /// </summary>
        /// <param name="mailConversationEntryLastErrorAnyOf"></param>
        /// <param name="mailConversationEntryLastErrorAnyOf1"></param>
        /// <param name="mailConversationEntryLastErrorAnyOf2"></param>
        public MailConversationEntryLastError(Option<MailConversationEntryLastErrorAnyOf?> mailConversationEntryLastErrorAnyOf, Option<MailConversationEntryLastErrorAnyOf1?> mailConversationEntryLastErrorAnyOf1, Option<MailConversationEntryLastErrorAnyOf2?> mailConversationEntryLastErrorAnyOf2)
        {
            MailConversationEntryLastErrorAnyOfOption = mailConversationEntryLastErrorAnyOf;
            MailConversationEntryLastErrorAnyOf1Option = mailConversationEntryLastErrorAnyOf1;
            MailConversationEntryLastErrorAnyOf2Option = mailConversationEntryLastErrorAnyOf2;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of MailConversationEntryLastErrorAnyOf
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailConversationEntryLastErrorAnyOf?> MailConversationEntryLastErrorAnyOfOption { get; private set; }

        /// <summary>
        /// Gets or Sets MailConversationEntryLastErrorAnyOf
        /// </summary>
        public MailConversationEntryLastErrorAnyOf? MailConversationEntryLastErrorAnyOf { get { return this.MailConversationEntryLastErrorAnyOfOption.Value; } set { this.MailConversationEntryLastErrorAnyOfOption = new(value); } }

        /// <summary>
        /// Used to track the state of MailConversationEntryLastErrorAnyOf1
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailConversationEntryLastErrorAnyOf1?> MailConversationEntryLastErrorAnyOf1Option { get; private set; }

        /// <summary>
        /// Gets or Sets MailConversationEntryLastErrorAnyOf1
        /// </summary>
        public MailConversationEntryLastErrorAnyOf1? MailConversationEntryLastErrorAnyOf1 { get { return this.MailConversationEntryLastErrorAnyOf1Option.Value; } set { this.MailConversationEntryLastErrorAnyOf1Option = new(value); } }

        /// <summary>
        /// Used to track the state of MailConversationEntryLastErrorAnyOf2
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MailConversationEntryLastErrorAnyOf2?> MailConversationEntryLastErrorAnyOf2Option { get; private set; }

        /// <summary>
        /// Gets or Sets MailConversationEntryLastErrorAnyOf2
        /// </summary>
        public MailConversationEntryLastErrorAnyOf2? MailConversationEntryLastErrorAnyOf2 { get { return this.MailConversationEntryLastErrorAnyOf2Option.Value; } set { this.MailConversationEntryLastErrorAnyOf2Option = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailConversationEntryLastError {\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailConversationEntryLastError" />
    /// </summary>
    public partial class MailConversationEntryLastErrorJsonConverter : JsonConverter<MailConversationEntryLastError>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailConversationEntryLastErrorJsonConverter" /> class.
        /// </summary>
        public MailConversationEntryLastErrorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailConversationEntryLastError" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailConversationEntryLastError Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            MailConversationEntryLastErrorAnyOf? mailConversationEntryLastErrorAnyOf = default;
            MailConversationEntryLastErrorAnyOf1? mailConversationEntryLastErrorAnyOf1 = default;
            MailConversationEntryLastErrorAnyOf2? mailConversationEntryLastErrorAnyOf2 = default;

            Utf8JsonReader utf8JsonReaderAnyOf = utf8JsonReader;
            while (utf8JsonReaderAnyOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderAnyOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderAnyOf.CurrentDepth)
                    break;

                if (utf8JsonReaderAnyOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderAnyOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderMailConversationEntryLastErrorAnyOf = utf8JsonReader;
                    ClientUtils.TryDeserialize<MailConversationEntryLastErrorAnyOf?>(ref utf8JsonReaderMailConversationEntryLastErrorAnyOf, jsonSerializerOptions, out mailConversationEntryLastErrorAnyOf);

                    Utf8JsonReader utf8JsonReaderMailConversationEntryLastErrorAnyOf1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<MailConversationEntryLastErrorAnyOf1?>(ref utf8JsonReaderMailConversationEntryLastErrorAnyOf1, jsonSerializerOptions, out mailConversationEntryLastErrorAnyOf1);

                    Utf8JsonReader utf8JsonReaderMailConversationEntryLastErrorAnyOf2 = utf8JsonReader;
                    ClientUtils.TryDeserialize<MailConversationEntryLastErrorAnyOf2?>(ref utf8JsonReaderMailConversationEntryLastErrorAnyOf2, jsonSerializerOptions, out mailConversationEntryLastErrorAnyOf2);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            Option<MailConversationEntryLastErrorAnyOf?> mailConversationEntryLastErrorAnyOfParsedValue = mailConversationEntryLastErrorAnyOf == null
                ? default
                : new Option<MailConversationEntryLastErrorAnyOf?>(mailConversationEntryLastErrorAnyOf);
            Option<MailConversationEntryLastErrorAnyOf1?> mailConversationEntryLastErrorAnyOf1ParsedValue = mailConversationEntryLastErrorAnyOf1 == null
                ? default
                : new Option<MailConversationEntryLastErrorAnyOf1?>(mailConversationEntryLastErrorAnyOf1);
            Option<MailConversationEntryLastErrorAnyOf2?> mailConversationEntryLastErrorAnyOf2ParsedValue = mailConversationEntryLastErrorAnyOf2 == null
                ? default
                : new Option<MailConversationEntryLastErrorAnyOf2?>(mailConversationEntryLastErrorAnyOf2);

            return new MailConversationEntryLastError(mailConversationEntryLastErrorAnyOfParsedValue, mailConversationEntryLastErrorAnyOf1ParsedValue, mailConversationEntryLastErrorAnyOf2ParsedValue);
        }

        /// <summary>
        /// Serializes a <see cref="MailConversationEntryLastError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailConversationEntryLastError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailConversationEntryLastError mailConversationEntryLastError, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            if (mailConversationEntryLastError.MailConversationEntryLastErrorAnyOfOption.IsSet && mailConversationEntryLastError.MailConversationEntryLastErrorAnyOfOption.Value != null)
            {
                MailConversationEntryLastErrorAnyOfJsonConverter mailConversationEntryLastErrorAnyOfJsonConverter = (MailConversationEntryLastErrorAnyOfJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(mailConversationEntryLastError.MailConversationEntryLastErrorAnyOfOption.Value.GetType()));
                mailConversationEntryLastErrorAnyOfJsonConverter.WriteProperties(writer, mailConversationEntryLastError.MailConversationEntryLastErrorAnyOfOption.Value, jsonSerializerOptions);
            }

            if (mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf1Option.IsSet && mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf1Option.Value != null)
            {
                MailConversationEntryLastErrorAnyOf1JsonConverter mailConversationEntryLastErrorAnyOf1JsonConverter = (MailConversationEntryLastErrorAnyOf1JsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf1Option.Value.GetType()));
                mailConversationEntryLastErrorAnyOf1JsonConverter.WriteProperties(writer, mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf1Option.Value, jsonSerializerOptions);
            }

            if (mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf2Option.IsSet && mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf2Option.Value != null)
            {
                MailConversationEntryLastErrorAnyOf2JsonConverter mailConversationEntryLastErrorAnyOf2JsonConverter = (MailConversationEntryLastErrorAnyOf2JsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf2Option.Value.GetType()));
                mailConversationEntryLastErrorAnyOf2JsonConverter.WriteProperties(writer, mailConversationEntryLastError.MailConversationEntryLastErrorAnyOf2Option.Value, jsonSerializerOptions);
            }

            WriteProperties(writer, mailConversationEntryLastError, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailConversationEntryLastError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailConversationEntryLastError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailConversationEntryLastError mailConversationEntryLastError, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
