// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// MailPostCrmNotesResponse200EventPayload
    /// </summary>
    public partial class MailPostCrmNotesResponse200EventPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostCrmNotesResponse200EventPayload" /> class.
        /// </summary>
        /// <param name="text">text</param>
        [JsonConstructor]
        public MailPostCrmNotesResponse200EventPayload(string text)
        {
            Text = text;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailPostCrmNotesResponse200EventPayload {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailPostCrmNotesResponse200EventPayload" />
    /// </summary>
    public partial class MailPostCrmNotesResponse200EventPayloadJsonConverter : JsonConverter<MailPostCrmNotesResponse200EventPayload>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailPostCrmNotesResponse200EventPayloadJsonConverter" /> class.
        /// </summary>
        public MailPostCrmNotesResponse200EventPayloadJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailPostCrmNotesResponse200EventPayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailPostCrmNotesResponse200EventPayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> text = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class MailPostCrmNotesResponse200EventPayload.", nameof(text));

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class MailPostCrmNotesResponse200EventPayload.");

            var reaconModelResult = new MailPostCrmNotesResponse200EventPayload(text.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="MailPostCrmNotesResponse200EventPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostCrmNotesResponse200EventPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailPostCrmNotesResponse200EventPayload mailPostCrmNotesResponse200EventPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailPostCrmNotesResponse200EventPayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailPostCrmNotesResponse200EventPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailPostCrmNotesResponse200EventPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailPostCrmNotesResponse200EventPayload mailPostCrmNotesResponse200EventPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailPostCrmNotesResponse200EventPayload.Text == null)
                throw new ArgumentNullException(nameof(mailPostCrmNotesResponse200EventPayload.Text), "Property is required for class MailPostCrmNotesResponse200EventPayload.");

            writer.WriteString("text", mailPostCrmNotesResponse200EventPayload.Text);

            foreach (var property in mailPostCrmNotesResponse200EventPayload.AdditionalProperties)
            {
                if (property.Key == "text") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
