// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ProductDomainFinderInput
    /// </summary>
    public partial class ProductDomainFinderInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDomainFinderInput" /> class.
        /// </summary>
        /// <param name="company">The server applies trim before validating {\&quot;type\&quot;:\&quot;string\&quot;,\&quot;minLength\&quot;:1,\&quot;maxLength\&quot;:500}.</param>
        [JsonConstructor]
        public ProductDomainFinderInput(string company)
        {
            Company = company;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The server applies trim before validating {\&quot;type\&quot;:\&quot;string\&quot;,\&quot;minLength\&quot;:1,\&quot;maxLength\&quot;:500}.
        /// </summary>
        /// <value>The server applies trim before validating {\&quot;type\&quot;:\&quot;string\&quot;,\&quot;minLength\&quot;:1,\&quot;maxLength\&quot;:500}.</value>
        [JsonPropertyName("company")]
        public string Company { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductDomainFinderInput {\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProductDomainFinderInput" />
    /// </summary>
    public partial class ProductDomainFinderInputJsonConverter : JsonConverter<ProductDomainFinderInput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDomainFinderInputJsonConverter" /> class.
        /// </summary>
        public ProductDomainFinderInputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProductDomainFinderInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProductDomainFinderInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> company = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "company":
                            company = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!company.IsSet)
                throw new ArgumentException("Property is required for class ProductDomainFinderInput.", nameof(company));

            if (company.IsSet && company.Value == null)
                throw new ArgumentNullException(nameof(company), "Property is not nullable for class ProductDomainFinderInput.");

            return new ProductDomainFinderInput(company.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ProductDomainFinderInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productDomainFinderInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProductDomainFinderInput productDomainFinderInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, productDomainFinderInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProductDomainFinderInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productDomainFinderInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProductDomainFinderInput productDomainFinderInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (productDomainFinderInput.Company == null)
                throw new ArgumentNullException(nameof(productDomainFinderInput.Company), "Property is required for class ProductDomainFinderInput.");

            writer.WriteString("company", productDomainFinderInput.Company);
        }
    }
}
