// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ProductUsageTransaction
    /// </summary>
    public partial class ProductUsageTransaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUsageTransaction" /> class.
        /// </summary>
        /// <param name="amount">amount</param>
        /// <param name="id">id</param>
        /// <param name="occurredAt">occurredAt</param>
        /// <param name="type">type</param>
        /// <param name="description">description</param>
        [JsonConstructor]
        public ProductUsageTransaction(int amount, Guid id, DateTimeOffset occurredAt, string type, string? description = default)
        {
            Amount = amount;
            Id = id;
            OccurredAt = occurredAt;
            Type = type;
            Description = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets OccurredAt
        /// </summary>
        [JsonPropertyName("occurredAt")]
        public DateTimeOffset OccurredAt { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductUsageTransaction {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OccurredAt: ").Append(OccurredAt).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProductUsageTransaction" />
    /// </summary>
    public partial class ProductUsageTransactionJsonConverter : JsonConverter<ProductUsageTransaction>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUsageTransactionJsonConverter" /> class.
        /// </summary>
        public ProductUsageTransactionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize OccurredAt
        /// </summary>
        public string OccurredAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ProductUsageTransaction" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProductUsageTransaction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> amount = default;
            Option<Guid?> id = default;
            Option<DateTimeOffset?> occurredAt = default;
            Option<string?> type = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "occurredAt":
                            occurredAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class ProductUsageTransaction.", nameof(amount));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ProductUsageTransaction.", nameof(id));

            if (!occurredAt.IsSet)
                throw new ArgumentException("Property is required for class ProductUsageTransaction.", nameof(occurredAt));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class ProductUsageTransaction.", nameof(type));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class ProductUsageTransaction.", nameof(description));

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class ProductUsageTransaction.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ProductUsageTransaction.");

            if (occurredAt.IsSet && occurredAt.Value == null)
                throw new ArgumentNullException(nameof(occurredAt), "Property is not nullable for class ProductUsageTransaction.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class ProductUsageTransaction.");

            var reaconModelResult = new ProductUsageTransaction(amount.Value!.Value!, id.Value!.Value!, occurredAt.Value!.Value!, type.Value!, description.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="ProductUsageTransaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productUsageTransaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProductUsageTransaction productUsageTransaction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, productUsageTransaction, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProductUsageTransaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productUsageTransaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProductUsageTransaction productUsageTransaction, JsonSerializerOptions jsonSerializerOptions)
        {
            if (productUsageTransaction.Type == null)
                throw new ArgumentNullException(nameof(productUsageTransaction.Type), "Property is required for class ProductUsageTransaction.");

            writer.WriteNumber("amount", productUsageTransaction.Amount);

            writer.WriteString("id", productUsageTransaction.Id);

            writer.WriteString("occurredAt", productUsageTransaction.OccurredAt.ToString(OccurredAtFormat));

            writer.WriteString("type", productUsageTransaction.Type);

            if (productUsageTransaction.Description != null)
                writer.WriteString("description", productUsageTransaction.Description);
            else
                writer.WriteNull("description");

            foreach (var property in productUsageTransaction.AdditionalProperties)
            {
                if (property.Key == "amount" || property.Key == "id" || property.Key == "occurredAt" || property.Key == "type" || property.Key == "description") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
