// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ProductCompanyUpdateOutput
    /// </summary>
    public partial class ProductCompanyUpdateOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductCompanyUpdateOutput" /> class.
        /// </summary>
        /// <param name="companyId">companyId</param>
        /// <param name="employeeRange">employeeRange</param>
        /// <param name="industry">industry</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public ProductCompanyUpdateOutput(Guid companyId, string? employeeRange = default, string? industry = default, string? name = default)
        {
            CompanyId = companyId;
            EmployeeRange = employeeRange;
            Industry = industry;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CompanyId
        /// </summary>
        [JsonPropertyName("companyId")]
        public Guid CompanyId { get; set; }

        /// <summary>
        /// Gets or Sets EmployeeRange
        /// </summary>
        [JsonPropertyName("employeeRange")]
        public string? EmployeeRange { get; set; }

        /// <summary>
        /// Gets or Sets Industry
        /// </summary>
        [JsonPropertyName("industry")]
        public string? Industry { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductCompanyUpdateOutput {\n");
            sb.Append("  CompanyId: ").Append(CompanyId).Append("\n");
            sb.Append("  EmployeeRange: ").Append(EmployeeRange).Append("\n");
            sb.Append("  Industry: ").Append(Industry).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProductCompanyUpdateOutput" />
    /// </summary>
    public partial class ProductCompanyUpdateOutputJsonConverter : JsonConverter<ProductCompanyUpdateOutput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductCompanyUpdateOutputJsonConverter" /> class.
        /// </summary>
        public ProductCompanyUpdateOutputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProductCompanyUpdateOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProductCompanyUpdateOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> companyId = default;
            Option<string?> employeeRange = default;
            Option<string?> industry = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "companyId":
                            companyId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "employeeRange":
                            employeeRange = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "industry":
                            industry = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!companyId.IsSet)
                throw new ArgumentException("Property is required for class ProductCompanyUpdateOutput.", nameof(companyId));

            if (!employeeRange.IsSet)
                throw new ArgumentException("Property is required for class ProductCompanyUpdateOutput.", nameof(employeeRange));

            if (!industry.IsSet)
                throw new ArgumentException("Property is required for class ProductCompanyUpdateOutput.", nameof(industry));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ProductCompanyUpdateOutput.", nameof(name));

            if (companyId.IsSet && companyId.Value == null)
                throw new ArgumentNullException(nameof(companyId), "Property is not nullable for class ProductCompanyUpdateOutput.");

            var reaconModelResult = new ProductCompanyUpdateOutput(companyId.Value!.Value!, employeeRange.Value!, industry.Value!, name.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="ProductCompanyUpdateOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productCompanyUpdateOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProductCompanyUpdateOutput productCompanyUpdateOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, productCompanyUpdateOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProductCompanyUpdateOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productCompanyUpdateOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProductCompanyUpdateOutput productCompanyUpdateOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("companyId", productCompanyUpdateOutput.CompanyId);

            if (productCompanyUpdateOutput.EmployeeRange != null)
                writer.WriteString("employeeRange", productCompanyUpdateOutput.EmployeeRange);
            else
                writer.WriteNull("employeeRange");

            if (productCompanyUpdateOutput.Industry != null)
                writer.WriteString("industry", productCompanyUpdateOutput.Industry);
            else
                writer.WriteNull("industry");

            if (productCompanyUpdateOutput.Name != null)
                writer.WriteString("name", productCompanyUpdateOutput.Name);
            else
                writer.WriteNull("name");

            foreach (var property in productCompanyUpdateOutput.AdditionalProperties)
            {
                if (property.Key == "companyId" || property.Key == "employeeRange" || property.Key == "industry" || property.Key == "name") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
