// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ProductCustomAttributeCreateInput
    /// </summary>
    public partial class ProductCustomAttributeCreateInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductCustomAttributeCreateInput" /> class.
        /// </summary>
        /// <param name="idempotencyKey">idempotencyKey</param>
        /// <param name="key">key</param>
        /// <param name="name">The server applies trim before validating {\&quot;type\&quot;:\&quot;string\&quot;,\&quot;minLength\&quot;:1,\&quot;maxLength\&quot;:500}.</param>
        [JsonConstructor]
        public ProductCustomAttributeCreateInput(string idempotencyKey, string key, string name)
        {
            IdempotencyKey = idempotencyKey;
            Key = key;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets IdempotencyKey
        /// </summary>
        [JsonPropertyName("idempotencyKey")]
        public string IdempotencyKey { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// The server applies trim before validating {\&quot;type\&quot;:\&quot;string\&quot;,\&quot;minLength\&quot;:1,\&quot;maxLength\&quot;:500}.
        /// </summary>
        /// <value>The server applies trim before validating {\&quot;type\&quot;:\&quot;string\&quot;,\&quot;minLength\&quot;:1,\&quot;maxLength\&quot;:500}.</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductCustomAttributeCreateInput {\n");
            sb.Append("  IdempotencyKey: ").Append(IdempotencyKey).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IdempotencyKey (string) maxLength
            if (this.IdempotencyKey != null && this.IdempotencyKey.Length > 200)
            {
                yield return new ValidationResult("Invalid value for IdempotencyKey, length must be less than 200.", new [] { "IdempotencyKey" });
            }

            // IdempotencyKey (string) minLength
            if (this.IdempotencyKey != null && this.IdempotencyKey.Length < 16)
            {
                yield return new ValidationResult("Invalid value for IdempotencyKey, length must be greater than 16.", new [] { "IdempotencyKey" });
            }

            if (this.Key != null) {
                // Key (string) pattern
                Regex regexKey = new Regex(@"^[a-z][a-z0-9_]{0,63}$", RegexOptions.CultureInvariant);

                if (!regexKey.Match(this.Key).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Key, must match a pattern of " + regexKey, new [] { "Key" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProductCustomAttributeCreateInput" />
    /// </summary>
    public partial class ProductCustomAttributeCreateInputJsonConverter : JsonConverter<ProductCustomAttributeCreateInput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductCustomAttributeCreateInputJsonConverter" /> class.
        /// </summary>
        public ProductCustomAttributeCreateInputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProductCustomAttributeCreateInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProductCustomAttributeCreateInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> idempotencyKey = default;
            Option<string?> key = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "idempotencyKey":
                            idempotencyKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!idempotencyKey.IsSet)
                throw new ArgumentException("Property is required for class ProductCustomAttributeCreateInput.", nameof(idempotencyKey));

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class ProductCustomAttributeCreateInput.", nameof(key));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ProductCustomAttributeCreateInput.", nameof(name));

            if (idempotencyKey.IsSet && idempotencyKey.Value == null)
                throw new ArgumentNullException(nameof(idempotencyKey), "Property is not nullable for class ProductCustomAttributeCreateInput.");

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class ProductCustomAttributeCreateInput.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ProductCustomAttributeCreateInput.");

            return new ProductCustomAttributeCreateInput(idempotencyKey.Value!, key.Value!, name.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ProductCustomAttributeCreateInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productCustomAttributeCreateInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProductCustomAttributeCreateInput productCustomAttributeCreateInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, productCustomAttributeCreateInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProductCustomAttributeCreateInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productCustomAttributeCreateInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProductCustomAttributeCreateInput productCustomAttributeCreateInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (productCustomAttributeCreateInput.IdempotencyKey == null)
                throw new ArgumentNullException(nameof(productCustomAttributeCreateInput.IdempotencyKey), "Property is required for class ProductCustomAttributeCreateInput.");

            if (productCustomAttributeCreateInput.Key == null)
                throw new ArgumentNullException(nameof(productCustomAttributeCreateInput.Key), "Property is required for class ProductCustomAttributeCreateInput.");

            if (productCustomAttributeCreateInput.Name == null)
                throw new ArgumentNullException(nameof(productCustomAttributeCreateInput.Name), "Property is required for class ProductCustomAttributeCreateInput.");

            writer.WriteString("idempotencyKey", productCustomAttributeCreateInput.IdempotencyKey);

            writer.WriteString("key", productCustomAttributeCreateInput.Key);

            writer.WriteString("name", productCustomAttributeCreateInput.Name);
        }
    }
}
