// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ProductPersonSummary
    /// </summary>
    public partial class ProductPersonSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductPersonSummary" /> class.
        /// </summary>
        /// <param name="companyDomain">companyDomain</param>
        /// <param name="email">email</param>
        /// <param name="id">id</param>
        /// <param name="company">company</param>
        /// <param name="firstName">firstName</param>
        /// <param name="lastName">lastName</param>
        /// <param name="position">position</param>
        [JsonConstructor]
        public ProductPersonSummary(string companyDomain, string email, Guid id, string? company = default, string? firstName = default, string? lastName = default, string? position = default)
        {
            CompanyDomain = companyDomain;
            Email = email;
            Id = id;
            Company = company;
            FirstName = firstName;
            LastName = lastName;
            Position = position;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CompanyDomain
        /// </summary>
        [JsonPropertyName("companyDomain")]
        public string CompanyDomain { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Company
        /// </summary>
        [JsonPropertyName("company")]
        public string? Company { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [JsonPropertyName("firstName")]
        public string? FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [JsonPropertyName("lastName")]
        public string? LastName { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [JsonPropertyName("position")]
        public string? Position { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductPersonSummary {\n");
            sb.Append("  CompanyDomain: ").Append(CompanyDomain).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProductPersonSummary" />
    /// </summary>
    public partial class ProductPersonSummaryJsonConverter : JsonConverter<ProductPersonSummary>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductPersonSummaryJsonConverter" /> class.
        /// </summary>
        public ProductPersonSummaryJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProductPersonSummary" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProductPersonSummary Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> companyDomain = default;
            Option<string?> email = default;
            Option<Guid?> id = default;
            Option<string?> company = default;
            Option<string?> firstName = default;
            Option<string?> lastName = default;
            Option<string?> position = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "companyDomain":
                            companyDomain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "company":
                            company = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "firstName":
                            firstName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastName":
                            lastName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "position":
                            position = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!companyDomain.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(companyDomain));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(email));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(id));

            if (!company.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(company));

            if (!firstName.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(firstName));

            if (!lastName.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(lastName));

            if (!position.IsSet)
                throw new ArgumentException("Property is required for class ProductPersonSummary.", nameof(position));

            if (companyDomain.IsSet && companyDomain.Value == null)
                throw new ArgumentNullException(nameof(companyDomain), "Property is not nullable for class ProductPersonSummary.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class ProductPersonSummary.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ProductPersonSummary.");

            var reaconModelResult = new ProductPersonSummary(companyDomain.Value!, email.Value!, id.Value!.Value!, company.Value!, firstName.Value!, lastName.Value!, position.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="ProductPersonSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productPersonSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProductPersonSummary productPersonSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, productPersonSummary, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProductPersonSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productPersonSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProductPersonSummary productPersonSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            if (productPersonSummary.CompanyDomain == null)
                throw new ArgumentNullException(nameof(productPersonSummary.CompanyDomain), "Property is required for class ProductPersonSummary.");

            if (productPersonSummary.Email == null)
                throw new ArgumentNullException(nameof(productPersonSummary.Email), "Property is required for class ProductPersonSummary.");

            writer.WriteString("companyDomain", productPersonSummary.CompanyDomain);

            writer.WriteString("email", productPersonSummary.Email);

            writer.WriteString("id", productPersonSummary.Id);

            if (productPersonSummary.Company != null)
                writer.WriteString("company", productPersonSummary.Company);
            else
                writer.WriteNull("company");

            if (productPersonSummary.FirstName != null)
                writer.WriteString("firstName", productPersonSummary.FirstName);
            else
                writer.WriteNull("firstName");

            if (productPersonSummary.LastName != null)
                writer.WriteString("lastName", productPersonSummary.LastName);
            else
                writer.WriteNull("lastName");

            if (productPersonSummary.Position != null)
                writer.WriteString("position", productPersonSummary.Position);
            else
                writer.WriteNull("position");

            foreach (var property in productPersonSummary.AdditionalProperties)
            {
                if (property.Key == "companyDomain" || property.Key == "email" || property.Key == "id" || property.Key == "company" || property.Key == "firstName" || property.Key == "lastName" || property.Key == "position") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
