// <auto-generated>
/*
 * Reacon API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Reacon.Sdk.Client;

namespace Reacon.Sdk.Model
{
    /// <summary>
    /// ProductAccountInfoOutput
    /// </summary>
    public partial class ProductAccountInfoOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductAccountInfoOutput" /> class.
        /// </summary>
        /// <param name="creditsAvailable">creditsAvailable</param>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="type">type</param>
        /// <param name="plan">plan</param>
        [JsonConstructor]
        public ProductAccountInfoOutput(int creditsAvailable, Guid id, string name, string type, string? plan = default)
        {
            CreditsAvailable = creditsAvailable;
            Id = id;
            Name = name;
            Type = type;
            Plan = plan;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CreditsAvailable
        /// </summary>
        [JsonPropertyName("creditsAvailable")]
        public int CreditsAvailable { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Plan
        /// </summary>
        [JsonPropertyName("plan")]
        public string? Plan { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductAccountInfoOutput {\n");
            sb.Append("  CreditsAvailable: ").Append(CreditsAvailable).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Plan: ").Append(Plan).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProductAccountInfoOutput" />
    /// </summary>
    public partial class ProductAccountInfoOutputJsonConverter : JsonConverter<ProductAccountInfoOutput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductAccountInfoOutputJsonConverter" /> class.
        /// </summary>
        public ProductAccountInfoOutputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProductAccountInfoOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProductAccountInfoOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;
            var additionalProperties = new Dictionary<string, JsonElement>();

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> creditsAvailable = default;
            Option<Guid?> id = default;
            Option<string?> name = default;
            Option<string?> type = default;
            Option<string?> plan = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "creditsAvailable":
                            creditsAvailable = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "plan":
                            plan = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            using (var reaconUnknownValue = JsonDocument.ParseValue(ref utf8JsonReader))
                                additionalProperties[localVarJsonPropertyName!] = reaconUnknownValue.RootElement.Clone();
                            break;
                    }
                }
            }

            if (!creditsAvailable.IsSet)
                throw new ArgumentException("Property is required for class ProductAccountInfoOutput.", nameof(creditsAvailable));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ProductAccountInfoOutput.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ProductAccountInfoOutput.", nameof(name));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class ProductAccountInfoOutput.", nameof(type));

            if (!plan.IsSet)
                throw new ArgumentException("Property is required for class ProductAccountInfoOutput.", nameof(plan));

            if (creditsAvailable.IsSet && creditsAvailable.Value == null)
                throw new ArgumentNullException(nameof(creditsAvailable), "Property is not nullable for class ProductAccountInfoOutput.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ProductAccountInfoOutput.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ProductAccountInfoOutput.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class ProductAccountInfoOutput.");

            var reaconModelResult = new ProductAccountInfoOutput(creditsAvailable.Value!.Value!, id.Value!.Value!, name.Value!, type.Value!, plan.Value!);
            foreach (var property in additionalProperties) reaconModelResult.AdditionalProperties[property.Key] = property.Value;
            return reaconModelResult;
        }

        /// <summary>
        /// Serializes a <see cref="ProductAccountInfoOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productAccountInfoOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProductAccountInfoOutput productAccountInfoOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, productAccountInfoOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProductAccountInfoOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="productAccountInfoOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProductAccountInfoOutput productAccountInfoOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (productAccountInfoOutput.Name == null)
                throw new ArgumentNullException(nameof(productAccountInfoOutput.Name), "Property is required for class ProductAccountInfoOutput.");

            if (productAccountInfoOutput.Type == null)
                throw new ArgumentNullException(nameof(productAccountInfoOutput.Type), "Property is required for class ProductAccountInfoOutput.");

            writer.WriteNumber("creditsAvailable", productAccountInfoOutput.CreditsAvailable);

            writer.WriteString("id", productAccountInfoOutput.Id);

            writer.WriteString("name", productAccountInfoOutput.Name);

            writer.WriteString("type", productAccountInfoOutput.Type);

            if (productAccountInfoOutput.Plan != null)
                writer.WriteString("plan", productAccountInfoOutput.Plan);
            else
                writer.WriteNull("plan");

            foreach (var property in productAccountInfoOutput.AdditionalProperties)
            {
                if (property.Key == "creditsAvailable" || property.Key == "id" || property.Key == "name" || property.Key == "type" || property.Key == "plan") throw new JsonException("Additional properties cannot override declared properties");
                writer.WritePropertyName(property.Key);
                property.Value.WriteTo(writer);
            }
        }
    }
}
